### ISSUE TITLE
As a manager, I can't see, but can edit works in admin set with review process

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#101]
### Descriptive summary
As a manager of an admin set, I can can't see works in review, but I can edit them. 
Using Admin Set: Test one-step work flow with faculty manager  - I had a reg user submit works. As the manager, I can't see them via Work View or via the Admin Set dashboard but you can edit them. Similar to the behavior seen in https://github.com/curationexperts/nurax/issues/72

So far as I can tell, I can see objects in admin sets that do not have workflows. 

@cpd3149 confirmed this. 

### Expected behavior
I can see what I can edit. 

### Actual behavior
Can't view, but can edit

![screen shot 2017-10-04 at 4 07 50 pm](https://user-images.githubusercontent.com/4356335/31197173-407ca132-a91e-11e7-8e22-3197581c7928.png)
![screen shot 2017-10-04 at 4 08 01 pm](https://user-images.githubusercontent.com/4356335/31197175-434c2ad6-a91e-11e7-8050-3f3b2b5949f7.png)

### Steps to reproduce the behavior
1. Create admin set with 1 step
2. Add manager, allow users to deposit
3. As non-manager, add work (keep the URL)
4. As manager visit URL
5. As manager go to admin set in dashboard, click title, try to edit via drop-down

**Comment by mjgiarlo** [comment]
@vantuyls @julesies Needs triage and ticketing in Hyrax.

**Comment by julesies** [comment]
@vantuyls you want to confirm this one first or shall I move? Chris could reproduce yesterday.

**Comment by vantuyls** [comment]
one reproduction is enough for me. thanks for moving.

**Comment by mjgiarlo** [comment]
Decided to close in hyrax.
