### ISSUE TITLE
Works "disappear" with deposit to Admin sets with combo: Release Embargo and Visibility Everyone

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#102]
### Descriptive summary
 

When submitting to admin sets 2 and 11, it defaults to "private setting" - so if the depositor doesn't actively click another setting, but hits save, the work disappears. As far as I can tell, the combo has to be embargo allowed and public visibility.

Here is the admin set setting. 
![screen shot 2017-10-05 at 11 58 38 am](https://user-images.githubusercontent.com/4356335/31237452-06090052-a9c5-11e7-967c-226e94b32060.png)

Here is the work view, where the setting does not move from private, like the others do. 
![screen shot 2017-10-05 at 11 47 19 am](https://user-images.githubusercontent.com/4356335/31237400-dcf9f9d2-a9c4-11e7-83bc-35dec4b814b4.png)

### Steps to reproduce the behavior

1. Create admin set with Embargo allowed, public visibility only
2. deposit work to admin set - do not change access control. 
3. Click save, work disappears. 

### Related work

I believe this is like https://github.com/curationexperts/nurax/issues/43 Sorry I didn't catch it before.

**Comment by heathergreerklein** [comment]
Confirmed---this is exactly what I saw when trying to add a work to admin set 11, making no change to the access control.

**Comment by julesies** [comment]
Thanks for checking this one @heathergreerklein ! @vantuyls @mjgiarlo blocker?

**Comment by mjgiarlo** [comment]
@julesies OK

**Comment by vantuyls** [comment]
seeing this also. not reported, but when i submit, i'm sent back to an empty form for a generic work.

**Comment by vantuyls** [comment]
moved to hyrax - https://github.com/samvera/hyrax/issues/1772

**Comment by mjgiarlo** [comment]
Fixed in Hyrax and Nurax has been updated.
