### ISSUE TITLE
Forgot Your Password?: Reset Password Gives Error

### ISSUE THREAD

**Issue by shlake** [samvera-labs/nurax-pre2023#104]
### Descriptive summary
Forgot Your Password?: Reset Password Gives Error

From Login screen, click "Forgot your password". Type in a "known" nurax user email (if an unknown email is typed, message is good: "Email not found"). Then click on the button: "Send me reset password instructions": Get the error see below.

### Rationale

User should be able to reset password.

### Expected behavior
Nurax should send an email with directions on how to reset a password.

### Actual behavior
On this page: https://nurax.curationexperts.com/users/password?locale=en
gave the error:

![screen shot 2017-10-06 at 9 01 13 am](https://user-images.githubusercontent.com/3809325/31278963-213c74e8-aa75-11e7-932f-09b2b198c362.png)

### Steps to reproduce the behavior
From Login screen, click "Forgot your password". Type in a "known" nurax user email (if an unknown email is typed, message is good: "Email not found"). Then click on the button: "Send me reset password instructions":

**Comment by acozine** [comment]
Thanks for testing all aspects of Nurax! This is a known issue - the code works fine, but the test server isn't hooked up to an smtp server. See #42.
