### ISSUE TITLE
Can Enter ORCID id in Incorrect Format

### ISSUE THREAD

**Issue by shlake** [samvera-labs/nurax-pre2023#105]
### Descriptive summary
When entering an ORCID id in Edit Profile, I can enter the following incorrect format and nurax is OK with it:  1234-1234-1234-1234567

### Rationale

Allowing incorrect ORCID ids makes the resultant URL not correct. Also there seems to be format checking, but is inconsistent (gives warning about some mis-formatting, but not this one).

### Expected behavior
If the 19 character string "0000-0000-0000-0000" is not entered (doesn't match), the warning should be issued.

### Actual behavior
Correct format, according to message is: 
1234-1234-1234-1234 (19 characters - which include the "-" dash)

But entering 1234-1234-1234-1234567 is not flagged as warning, but ORCID is "saved".

![screen shot 2017-10-06 at 10 49 21 am](https://user-images.githubusercontent.com/3809325/31283612-18198090-aa84-11e7-98ee-218ea37924b9.png)

### Steps to reproduce the behavior

1. Go to Edit Profile
2. Enter this string in the ORCID field: 1234-1234-1234-1234567
3. Click save profile.

**Comment by mjgiarlo** [comment]
Have a fix for this in Hyrax: https://github.com/samvera/hyrax/pull/1776

Thanks, @shlake!
