### ISSUE TITLE
Admin set release option, can't return to default (Which makes Lease not work)

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#107]
Reported by @rjkati
### Descriptive summary
When creating an admin set, you can opt not to set anything under Release and Visibility: Release. However, if you click any of the release settings here, you can not Unclick (return to default). AFAICT, the only way to allow the option of Lease to work in the Work deposit form is to have nothing selected under "Release". 

### Rationale

Either have a way to clear settings in the admin set, or add an option "any setting" or something. 

### Steps to reproduce the behavior

1. Create a new admin set, do not click any setting under release
2. submit work with lease.
3. Change admin set by clicking any radio button to any setting under Release
4. Can't submit leased works, can't unclick Release Setting.

**Comment by mjgiarlo** [comment]
@julesies Chatted with @vantuyls today and we thought this was not a blocker. How do you feel?

**Comment by julesies** [comment]
@mjgiarlo @vantuyls clearing up the implications of this AFAICT:
so if you create a new admin set and take the “default setting” on the admin set for release and vis…meaning you don’t select any radio button…then a user can submit a work with a lease.

however if the repo admin ever clicks any of those radio buttons, even by accident to click around…they’ve unknowingly disabled leases for that admin set completely

**Comment by julesies** [comment]
@mjgiarlo talked to @vantuyls who said blocker on this, so moving to hyrax.

**Comment by mjgiarlo** [comment]
Yeah, leases don't really "fit" with Admin Set release options. I'm not sure this is a bug, but rather a gap in technical and user design.

**Comment by julesies** [comment]
@mjgiarlo could we just add a "None" radio button under release? Not sure how hard that is, but I think that would be a simple UI way to avoid this problem....

**Comment by mjgiarlo** [comment]
@julesies If an AS has "No Delay" selected, are leases still busted?

**Comment by julesies** [comment]
@mjgiarlo yeah, if No delay is chosen, Leases are busted (which is actually what prohibits leased works because it really means "Do not allow embargo or lease"). 

I was thinking this approach would be what any new admin set is by default so that 1. "none" would be the default setting and 2. the setting would mean leases are allowed but not enforced. Now, since the "no delay option" already exits a better wording would be something like Release: "Varies, let depositor decide release". 

To be clear, this setting exists as the default admin set setting, there is just no indication of it in the UI.

What do you think?

**Comment by mjgiarlo** [comment]
@julesies OK, so the two issues are:

1. `No Delay` should be selected in the UI (not a blocker?)
2. Selecting `No Delay` should not prevent leases from being used (probably needs discussion with @hannahfrost and @vantuyls)

?

**Comment by julesies** [comment]
@mjgiarlo i think we need the following under Release:
1. "Varies, allow depositor to decide" (allows leases, is actually the default setting but you can't redo a mistake in choosing one of the other buttons)
2. "No delay, everything is public immediately" (already exists) 
3.  "Varies with embargo"
4. "Delay all works until xyz Date" 


Does this make sense? We need to add a new radio button for the default setting - which is number one above, and is the invisible default setting.

**Comment by mjgiarlo** [comment]
@julesies I think it depends on what the desired behavior of "No Delay" is. Do we want "No Delay" to prevent leases as well as embargoes? If so, I think we need that extra item you suggest. If not, we have a bug to fix (and should also set default in UI to "No Delay").

@vantuyls @julesies @hannahfrost

**Comment by vantuyls** [comment]
i think that "no delay" suggests that the Release selected will happen immediately, thus embargo and lease should be disabled if "no delay" is selected.

**Comment by hannahfrost** [comment]
+1

**Comment by mjgiarlo** [comment]
Fixed in Hyrax and Nurax confirmed updated with the fix. See below:

![screenshot from 2017-10-11 12-22-57](https://user-images.githubusercontent.com/131982/31461649-0279889e-ae7f-11e7-812a-c619c90fa910.png)

Thanks, all!
