### ISSUE TITLE
Conflicting information about presence of files when  a work is created

### ISSUE THREAD

**Issue by starsplatter** [samvera-labs/nurax-pre2023#110]
### Descriptive summary

After creating a work, the top of the screen says files are being processed but the bottom of the screen says the work has no files. If you then edit the work to see what's happening, no files are listed on the files tab (because they are still being processed?)

### Rationale

Things don't stay in this state for long but it is very jarring when it happens.

### Expected behavior
Accurate reflection of the presence of files

### Actual behavior
Conflicting information about presence of files

### Steps to reproduce the behavior

1. Create a work
2. Add files
3. Save the work and scroll to the bottom of the work screen
4. Edit the work again.

![screen shot 2017-10-13 at 9 43 17 am 2](https://user-images.githubusercontent.com/2148239/31549386-ff58c0ca-affb-11e7-88fd-2ffd84812861.png)
Conflicting flash messages

![screen shot 2017-10-13 at 9 43 49 am 2](https://user-images.githubusercontent.com/2148239/31549387-ff6bb162-affb-11e7-9c4c-51dd8edc5994.png)
Edit screen after saving the work with files.

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by mjgiarlo** [comment]
I believe we have this ticketed in Hyrax too: https://github.com/samvera/hyrax/issues/495

**Comment by vantuyls** [comment]
ping awead 2.x
