### ISSUE TITLE
Based Near is missing its facet and field labels

### ISSUE THREAD

**Issue by starsplatter** [samvera-labs/nurax-pre2023#111]
### Descriptive summary

"Based Near" location facet is getting the default humanization for its label.

![screen shot 2017-10-13 at 10 45 15 am 2](https://user-images.githubusercontent.com/2148239/31551807-a8b3bf4c-b003-11e7-8cd9-7604bd8eaf11.png)

**Comment by vantuyls** [comment]
2.x

**Comment by mjgiarlo** [comment]
Redeploying Nurax now to pick up this fix. Heads-up, @vantuyls @julesies

**Comment by julesies** [comment]
@starsplatter mind re-testing?

**Comment by starsplatter** [comment]
Confirmed!

**Comment by starsplatter** [comment]
@mjgiarlo @jcoyne Sorry, it looks like the field label in the index view still says tesim. Maybe that this one didn't get fixed with the others is a bug itself? (Actually looking at the commit, it's probably because the blacklight end has its own translations that have to be maintained?)

![screen shot 2017-11-03 at 10 27 29 am 2](https://user-images.githubusercontent.com/2148239/32378658-aecf5204-c081-11e7-9bc7-dd4f74410857.png)

**Comment by jcoyne** [comment]
Oops, I just did the facet fix. I didn’t realize it was broken in two places.

**Comment by no-reply** [comment]
This is closed per @jcoyne's comment. I can confirm that it's closed as of Hyrax ref 583da6ae6a
