### ISSUE TITLE
As a user I expect to be able to set the thumbnail for a work from the file manager 

### ISSUE THREAD

**Issue by starsplatter** [samvera-labs/nurax-pre2023#112]
### Expected behavior
I would expect changing the representative media in the file manager to change the item's thumbnail or to give me the option to also change the thumbnail.

### Actual behavior
I can select a representative file in the file manager but this does not change the thumbnail. The option to change the thumbnail is buried 'additional fields' on the metadata edit screen.

**Comment by mjgiarlo** [comment]
Did you also change the thumbnail or just the representative media? Tbh, I don't totally grok the purpose of rep. media -- this is ripe for digging into. Thanks!

**Comment by starsplatter** [comment]
Okay, I think this is because there's some UX disconnect between what you can do in the file manager and what you can do with the rep media and thumbnail fields in the metadata.

So right now if you change representative media in file manager, it does change the show page image and it does change what file gets downloaded. It does NOT change the thumbnail, because thumbnail selection is not represented in the file manager. This means in the search results you'll see a different image than on the show page. Additionally, thumbnail is down in 'additional fields' which means it is easy to just never notice it (like me).

Reviewing this, I think from the developer standpoint there is not a bug but from the UX standpoint it is pretty rough. I will retitle it more accurately and I think take bug off but leave the UX label.

**Comment by mjgiarlo** [comment]
@starsplatter Okie dokie. Yes, indeed, the UX could stand to improve! :clap:

**Comment by vantuyls** [comment]
2.x enhancement

**Comment by chrisdaaz** [comment]
this works for me.
