### ISSUE TITLE
As a repo admin, I want to manage embargoes and leases via the Dashboard

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/nurax-pre2023#114]
### Descriptive summary
For testing purposes, I had to use (paste) URLs to get to the managing embargoes/leases pages. 

**Leases:**
- https://nurax.curationexperts.com/leases?locale=en

**Embargoes:**
- https://nurax.curationexperts.com/embargoes?locale=en

### Rationale
Currently there is no option on the Dashboard to manage embargoes/leases, but users should be able to have this feature be an option available on the Dashboard.

**Comment by vantuyls** [comment]
2.x feature

**Comment by julesies** [comment]
fixed
