### ISSUE TITLE
Make release/vis language more clear

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#116]
### Descriptive summary
This ticket started as trying to understand why leases were not working, but has been modified to suggest the language of that screen make more clear the impact on the depositor as well as what settings allow lease and private setting. 

These two settings, prohibit the depositor from selecting a lease.

Do not allow leases: 
![screen shot 2017-10-18 at 2 00 15 pm](https://user-images.githubusercontent.com/4356335/31734608-3a735458-b40d-11e7-8a9d-759344ddce36.png)
![screen shot 2017-10-18 at 1 59 08 pm](https://user-images.githubusercontent.com/4356335/31734618-40489dc0-b40d-11e7-8898-e635db7d7bca.png)

This one does allow leases:
![screen shot 2017-10-18 at 2 01 49 pm](https://user-images.githubusercontent.com/4356335/31734627-4876beb4-b40d-11e7-88a0-d5f57ff67d47.png)

Thinking we need to clarify language on this screen at the least.

**Comment by mjgiarlo** [comment]
@hannahfrost @ggeisler @julesies @vantuyls Is clarifying language sufficient, or should we, e.g., disable certain controls under `Visibility` when `Release` is `Varies - Allow depositor to decide`?

(I'm kinda regretting making the options on this screen diverge from the underlying work access controls, thereby making it difficult to reconcile work and admin set access controls in the UI.)

**Comment by julesies** [comment]
So I don't want to add complexity/work but I've been thinking about this a little, would something along the lines of the pic below would help? I'm not totally sure, but I don't think it introduces any new functionality... hmmm maybe the "keep all works" part does? 

One thing that is confusing about this screen now, is the relationship b/w the release and vis as well as the mixing of "collection settings" and "embargo policy". So below, the top section is more about the visibility settings for the entire set and the bottom is about the embargo policy you want to enforce for like an IR use case. It also maybe makes it more clear what setting you have to choose to enable leases. Embargo policies would have to work with the top 3 under visibility. Also I'm getting a little 🙃 with testing all the Release and Vis combos, so I may be way off. Thanks for hearing me out!

![22641940_10160010837545643_22490086_o](https://user-images.githubusercontent.com/4356335/31750419-f559a5a2-b44d-11e7-955b-1d7c4e64e20c.jpg)

**Comment by vantuyls** [comment]
i'm kind of confused about whats going on here, but i wonder if some explanatory text at the top of this page could clarify for the purposes of this release?

**Comment by julesies** [comment]
Okay, below is a suggestion to help clear up what is happening with these settings.  This language matches and makes more explicit what happens to the depositor when you choose them. These are language edits only. In addition, please note this identifies what setting combo must be used to allow leases...
![screen shot 2017-10-25 at 1 14 15 pm](https://user-images.githubusercontent.com/4356335/32012679-a8c0f3e2-b986-11e7-8d30-e08ea1e88725.png)

**Comment by vantuyls** [comment]
i think this clarifies things sufficiently to move forward. @hannahfrost @ggeisler @julesies can we ship?

**Comment by chrisdaaz** [comment]
fwiw, i think it's okay to disable the `lease` option when visibility is set to `institution` (i.e. the first screenshot). i agree with the language clarification suggested by @julesies

**Comment by julesies** [comment]
I'm not sure if this is totally clear in the above:

- lease ONLY works with the exact combo of settings shown above. 
- Private ONLY work with No embargo allowed setting

**Comment by julesies** [comment]
Updated language as an option to make Private combo setting clear. 
![screen shot 2017-10-25 at 5 24 20 pm](https://user-images.githubusercontent.com/4356335/32024114-68c34470-b9a9-11e7-8f44-997b4d076031.png)

**Comment by vantuyls** [comment]
Needs:
UIX work for 2.x series fixes
Language added for 2.0 release

**Comment by hannahfrost** [comment]
@julesies This latest mockup, with the added language, is exceptionally clear and specific. Great suggestion! 

For "Allow depositor to choose settings", the phrase "leases are allowed" only appears for the first radio button suboption, but wouldn't leases be a possibility for the other two suboptions too? If so, could this overall option be described as "Allow depositor to choose embargo settings; leases are allowed", and then dropped off the first suboption description (because redundant)?

My only other thought is, after looking over these phrases so carefully, I notice that the phrasing for the options under Release is not particularly consistent. Should "No embargoes or leases allowed" be changed to "Do not allow embargoes or leases"?  Not a big deal, but it does improve the consistency a bit.

cc @vantuyls @ggeisler

**Comment by ggeisler** [comment]
@julesies I just have some additional wording suggestions, for grammar and consistency purposes:

- Intro sentence (several minor changes):
> Release and visibility settings determine the options available to depositors when submitting a work to this administrative set. Changes to these settings do not affect previously deposited works.

- Agree with @hannahfrost's suggestion about changing to "Do not allow embargoes or leases"

- There are at least two places where the term "admin set" is used. These should be written out in full: "administrative set".

- For the second option under Visibility, there should be a period at the end of "Must use this option to allow leases." (If a list item has multiple sentences, they should all end in periods.)

- For the last bullet on the page, the second sentence is inconsistent in capitalization and abbreviates a term. It should read "Access is restricted to repository administrators, managers, and viewers of the set."

**Comment by julesies** [comment]
thanks @hannahfrost and @ggeisler! regarding the lease option, the only setting that currently allows leases is as shown, which may be a bug/unintentional. Once the language is updated, I'll test again to make sure.

**Comment by julesies** [comment]
was fixed in 2.0
