### ISSUE TITLE
Add Rebekah and Jenn as Nurax Repo Admin

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#117]
Can you add @rjkati and @starsplatter  as a Repo Admin users for Nurax so they can test Admin features?

The nurax account are rkati@email.unc.edu  and 

Thanks!

**Comment by mjgiarlo** [comment]
@acozine If you wouldn't mind reminding me: is this something I can tweak in `role_map.yml` and push, or is this a controlled config file that needs editing on the server? I should be able to do either, IIRC.

**Comment by acozine** [comment]
@mjgiarlo to add admin users for the UI, you can tweak `role_map.yml` and push. The only config files that have to be edited on the server are the linked (or shared) files for Capistrano. See https://github.com/curationexperts/nurax/blob/master/config/deploy.rb#L24.

**Comment by mjgiarlo** [comment]
@acozine thx!

@julesies done, and redeploying. cc: @rjkati @starsplatter
