### ISSUE TITLE
Maintain Visibility Setting When Transferring Ownership of a Work

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#135]
### Descriptive summary

When you transfer a work to another user, the work's visibility setting is changed to Private. Work ownership transfers should maintain the visibility settings of the work as they were before the transfer.

### Rationale

The unexpected change in visibility settings adds a task for a user when they accept ownership of a public, embargoed, or institution-only work. The new owner of the work might not know the original visibility setting of the work. This creates confusion.

### Expected behavior

Visibility settings should not change during the ownership transfer between users.

### Actual behavior

Visibility is changed to Private for all transferred works.

### Steps to reproduce the behavior

1. User A creates a Work and sets the visibility to public (makes sure the admin set the does not have a mediated workflow activated)
2. User A transfers the work to User B
3. User B accepts the work
4. Check the visibility status

**Comment by jcoyne** [comment]
Is this bug specific to Nurax or should it be in the Hyrax repo?

**Comment by julesies** [comment]
@jcoyne i can't tell if it exists on 2.0 since nurax is on CE branch now. if 2.0, then it needs to move. @vantuyls was going to check his local set up, unless you know!

**Comment by chrisdaaz** [comment]
I first noticed this on my institution's app, which is on Hyrax 1.04, so I doubt this is specific to NURAX.

**Comment by julesies** [comment]
@chrisdaaz ah thanks! move to hyrax then!

**Comment by chrisdaaz** [comment]
Moved to https://github.com/samvera/hyrax/issues/2293

**Comment by julesies** [comment]
@chrisdaaz is this resolved?

**Comment by julesies** [comment]
@chrisdaaz nvm i see it's open.
