### ISSUE TITLE
Has model ssim showing in facets for Dashboard: collections

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#136]
When faceting in collections, you see odd words. 

 
![screen shot 2017-12-01 at 4 04 11 pm](https://user-images.githubusercontent.com/4356335/33503476-d9ae697e-d6b1-11e7-9cec-5bc529e1315e.png)

**Comment by elrayle** [comment]
PR https://github.com/samvera/hyrax/pull/2564 fixed the odd words.  But I noticed that this filter only shows Admin Sets.  It does not show other collection types.

**Comment by julesies** [comment]
verified fixed.
