### ISSUE TITLE
Pre-existing collections say "collections" and "user collections"

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#137]
These are the same collections appearing twice, I believe...
![screenshot](https://user-images.githubusercontent.com/4356335/33503515-0533943e-d6b2-11e7-858f-cdfb0f59d111.png)

**Comment by mjgiarlo** [comment]
This may be due to the hiccough we experienced when I attempted to upgrade to the CE branch, failed, tried to hand-edit in a new collection type, and then used @elrayle's instructions after a bug was fixed. Could be this is a `#wontfix` or a data clean-up ticket.

**Comment by mjgiarlo** [comment]
Your thoughts on this, @elrayle?

**Comment by elrayle** [comment]
Fixed by https://github.com/samvera/hyrax/pull/2564
