### ISSUE TITLE
should admin sets have the same icons as collections now?

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#139]
Looks like in this view, Admin sets share an icon with works, maybe it should match collections?

![screen shot 2017-12-01 at 4 38 08 pm](https://user-images.githubusercontent.com/4356335/33504609-19d5145e-d6b6-11e7-8eef-dce2710d6f1e.png)

**Comment by elrayle** [comment]
@ggeisler Seems like a UI/UX judgement call.

**Comment by ggeisler** [comment]
I agree that the icon for Admin Set should be the same one used for Collection, rather than the one for a work.

**Comment by elrayle** [comment]
https://github.com/samvera/hyrax/issues/2603

**Comment by julesies** [comment]
Okay for new admin sets this work, but for existing, they show the work icon

![screen shot 2018-04-05 at 10 28 31 am](https://user-images.githubusercontent.com/4356335/38372219-465c128a-38bc-11e8-8a89-74e4f93b9690.png)

**Comment by elrayle** [comment]
@vantuyls This is a case of existing admin sets created in pre-2.1.0.  The default icon is not just used, it is assigned.  So if we want to update it for all, the migration service would need to...
* verify the admin  set is using the default icon and not an assigned thumbnail
* if using the default, update it to the new default one that is the same as collections

OPTION 1: Don't change default icons for existing admin sets (time estimate: 0)
OPTION 2: Use the process described above to have the migration service update the default icon (time estimate: ?)

**Comment by julesies** [comment]
Decision was to not update existing admin set icons pre 2.1
