### ISSUE TITLE
Add new committers and update to collaborator approach

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#14]
@acozine Thanks!

- Add @jcoyne and @smithjp ( Jennifer is UNC Hyrax Dev) as committers. 

- Update team member group approach from member to collaborators.

**Comment by acozine** [comment]
Original Nurax Committers team (@geekscruff @mjgiarlo @cam156) converted to Collaborators. Invitations to collaborate sent to @jcoyne and @smithjp.
