### ISSUE TITLE
"Sort by" dropdown options on Collection Public View page are garbly

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#140]
Here is a link https://nurax.curationexperts.com/collections/4j03cz680?locale=en 

![screen shot 2017-12-01 at 4 45 05 pm](https://user-images.githubusercontent.com/4356335/33504847-1d842724-d6b7-11e7-8d5c-e2cb063ce7d0.png)

**Comment by elrayle** [comment]
This is fixed at Hyrax master by https://github.com/samvera/hyrax/pull/2589.  It will be merged into Hyrax collections-sprint soon, hopefully tomorrow.

**Comment by julesies** [comment]
confirmed fixed
