### ISSUE TITLE
Add Brian as Repo Administrator

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/nurax-pre2023#143]
### Descriptive summary

Add the brian.mcbride account to the Repo Admin group.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

Adding Brian to the Repo Admin Group will allow him to test the new collection administration functionality in the latest version of Hyrax. And test other components of the system.

### Expected behavior

Admin access.

### Actual behavior

Currently does not have admin access.

### Steps to reproduce the behavior

1. Do this Add Brian to Repo Admin Group
1. Then do this... Notify Brian

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by julesies** [comment]
@brianmcbride what email would you use? this one? brian.mcbride (at) utah (dot) edu

**Comment by julesies** [comment]
@brianmcbride can  you check your status? you should have access now.

**Comment by julesies** [comment]
@brianmcbride actually not quite ready...we are waiting for a merge -hopefully resolved today but I'll let you know when it's done!

**Comment by julesies** [comment]
@brianmcbride can  you test?
