### ISSUE TITLE
Add Admin Set title on edit view?

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#145]
### Descriptive summary

Collections now have a title showing on the edit page which is really helpful. Can we do that for Admin Sets too?

Collection:

![screen shot 2017-12-14 at 11 15 58 am](https://user-images.githubusercontent.com/4356335/34003045-414d272c-e0c2-11e7-8243-25f92a19ed89.png)

Admin Set:

![screen shot 2017-12-14 at 11 30 40 am](https://user-images.githubusercontent.com/4356335/34003069-52e212c2-e0c2-11e7-967a-9cb2cda7265f.png)

**Comment by elrayle** [comment]
This seems very doable.  I copied this to Hyrax https://github.com/samvera/hyrax/issues/2601.

@julesies Do you close Nurax issues when they are copied over to hyrax?

**Comment by julesies** [comment]
@elrayle we wait until confirmed tested/implemented and then close (so we can keep up with bug fix verification). I'll make sure to write this up in the testing process docu I'm doing.

**Comment by elrayle** [comment]
Fixed by https://github.com/samvera/hyrax/pull/2652
