### ISSUE TITLE
Adding a new work to an existing Collection throws error

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#147]
### Descriptive summary
Adding a new work to an existing collection causes the "Something Went Wrong" error. 

The following scenarios do work:
Adding an existing work to an existing collection
Adding a new work to a new collection

Steps to reproduce:
1. Create a new work
2. in Relationships tab, select an existing collection (can use JRR Test)
3. Hit save
4. SWW

**Comment by elrayle** [comment]
PR https://github.com/samvera/hyrax/pull/2111 fixed the problem combined with running the repair_migrated_collections script.  A db migration was also required.

This is now fixed.
