### ISSUE TITLE
After deleting Admin Set, you are directed to an Admin Set page 

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#148]
### Descriptive summary
After deleting an admin set, you are directed to an old view of the admin sets dashboard (at least I think that is what is happening). Should be directed to the Collections view again. 

![screen shot 2017-12-15 at 12 19 29 pm](https://user-images.githubusercontent.com/4356335/34052940-823225f0-e192-11e7-902f-513a52187135.png)

1. Delete an admin set from dashboard.
2. Get to "admin set" view.

**Comment by elrayle** [comment]
I believe this to be fixed.

Tested with...
* Dashboard -> Collections -- create 2 Admin Sets with names 'AS - delete from index' and 'AS - delete from AS show'
* Dashboard -> Collections -> action menu for 'AS - delete from index' -> Delete collection -> Delete

Verify still on Dashboard -> Collections page

* Dashboard -> Collections -> click title 'AS - delete from AS show' -> Delete -> Ok

Verify forwarded to Dashboard -> Collections page

**Comment by elrayle** [comment]
@julesies Can you confirm fixed and close?

**Comment by julesies** [comment]
confirmed fixed.
