### ISSUE TITLE
Video and audio files do not download properly on view pages. All player buttons not working on Work View

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#153]
### Descriptive summary
For both the work view and file set pages, video files and audio files do not download properly. This was tested on Chrome and Safari on Mac.

On the work view page, the full screen and download buttons do not work at all.
here is an example: https://nurax.curationexperts.com/concern/images/r494vk17h?locale=en

On the fileset page, fullscreen and download buttons work, but downloads the wrong file. See audio download example. 

![screen shot 2017-12-19 at 12 52 40 pm](https://user-images.githubusercontent.com/4356335/34171206-87574764-e4bb-11e7-8068-70b7aef421b6.png)

On the work view page, under Items: if one chooses "Select an action: download" on a video file, it downloads the proper file. 

![screen shot 2017-12-19 at 12 50 40 pm](https://user-images.githubusercontent.com/4356335/34171189-7abb75fc-e4bb-11e7-9150-9da796e053e2.png)

### Steps to reproduce the behavior

1. Navigate to a video or audio work
2. try to use the player buttons
3. click the download button
4. navigate to fileset page
5. try to use the player buttons
6. click the download button

**Comment by jcoyne** [comment]
I believe this is fixed by https://github.com/samvera/hydra-head/pull/427

**Comment by mjgiarlo** [comment]
@jcoyne it could be that, but it could also be that recent CSS changes now occlude the download button. Issue needs analysis.

**Comment by jenlindner** [comment]
@julesies I can't reproduce all of the bugs on Mac Firefox; the only one I'm seeing there is the fullscreen for video. It's definitely buggier on Safari and Chrome (display is broken), but I can download fileset videos from both and play the audio. But the video player doesn't load properly in the work views, see screenshot.

<img width="1064" alt="not_good_safari" src="https://user-images.githubusercontent.com/186452/34220521-8d097a6e-e57a-11e7-95d1-3085856fd45c.png">

<img width="1117" alt="not_good_chrome" src="https://user-images.githubusercontent.com/186452/34220699-1f891444-e57b-11e7-8053-e153490f9088.png">


So can we be more specific about browsers and platforms here?

**Comment by julesies** [comment]
@jenlindner yeah i was on Chrome and Safari - Mac. 

can you verify that the same file is downloaded from fileset and viewer?

**Comment by julesies** [comment]
not sure what @mjgiarlo was testing on - windows?

**Comment by mjgiarlo** [comment]
Ubuntu Linux and Chrome.

**Comment by jenlindner** [comment]
@julesies Okay, thanks. No, just that you can download from the filesets actions. I don't see a download button in Firefox or Safarai, and it's obstructed in Chrome.

**Comment by julesies** [comment]
@jenlindner ah ok. So when I am on the filesets view page and push the download on player - it actually downloads a file, but it's the wrong file.

**Comment by julesies** [comment]
@jenlindner the was a PR in master that redid the UI for the work view page (not sure about fileset view). Since CE branch was rebased against master - it pulled in these changes I believe. @mjgiarlo is probably a better person to say more as I've reached the limit of my knowledge 😆

**Comment by jenlindner** [comment]
@julesies Ah, I think I know which PR might be in play here. @mjgiarlo, do you know who might have done the UI work on the recent PR, and if they might be wiling to look at how things broke here?

**Comment by mjgiarlo** [comment]
@jenlindner I believe it was either @jcoyne or @aaron-collier.

**Comment by jenlindner** [comment]
Hi @julesies, we had some discussion about these issues on the tech call today, I'm tagging @elrayle  so she can look at them. We also discussed the need for a better testing process in general, covering things like regression criteria, code coverage, and it seems like we might want to schedule some time to try and come up with something that sorts us out a little better on those things. @no-reply and @jcoyne and @vantuyls are interested in moving on these things soon, in order to get the next releases as stable as we can get them. Any thoughts on that?

**Comment by julesies** [comment]
@jenlindner cool, yeah sounds like a call is happening. I can see a complementary set of process and recs for the testing coverage as you suggest, but that is outside of what I can do and probably needs a dev to coordinate? I can clarify this page as it's meant to be iterated on throughout this year. https://wiki.duraspace.org/display/samvera/Hyrax+Testing+and+Release+Process

**Comment by jenlindner** [comment]
@julesies Nice, that page is great. Yes, it does sound like we want to fill out the dev testing part, I can probably help coordinate that.

**Comment by elrayle** [comment]
It seems highly unlikely this is a CE issue.  We didn't make any changes to work show page.  Did anyone test it against current master?

**Comment by jenlindner** [comment]
@elrayle see the above comment: @jenlindner the was a PR in master that redid the UI for the work view page (not sure about fileset view). Since CE branch was rebased against master - it pulled in these changes I believe.

**Comment by elrayle** [comment]
@jenlindner That was what I expected.  Thanks for the clarification.

**Comment by julesies** [comment]
update on this ticket with the latest code on Nurax:  Playback for audio/video is working in Chrome at the link above. The download button on both audio and video is still downloading a bad file.

**Comment by julesies** [comment]
another update: Safari looks like this for audio and video:  
![screen shot 2018-02-12 at 3 13 33 pm](https://user-images.githubusercontent.com/4356335/36117367-532cee18-1007-11e8-9937-aa209c7620d4.png)

**Comment by julesies** [comment]
@elrayle this is ready to retest? Not seeing the change and look like the PR and issues are open?

**Comment by elrayle** [comment]
PR https://github.com/samvera/hyrax/issues/2795 at least partially fixes this.

**Comment by julesies** [comment]
The download links are working perfectly. The player is busted in Safari.

**Comment by julesies** [comment]
this was fixed.
