### ISSUE TITLE
Add Johannes as Repo Administrator

### ISSUE THREAD

**Issue by jmfrenzel** [samvera-labs/nurax-pre2023#154]
### Descriptive summary
Add the jmfrenzel account to the Repo Admin group.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.
Adding BJohannes to the Repo Admin Group will allow him to test the (new) German translation  in the latest version of Hyrax. And test other components of the system.

### Expected behavior
Admin access.

### Actual behavior
Currently does not have admin access.

### Steps to reproduce the behavior

1.   Do this Add Johannes to Repo Admin Group
1.  Then do this... Notify Johannes 

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by jmfrenzel** [comment]
Thanks for adding me to the admin, @cjcolvar. By some reason :sweat_smile: I forgot to add my nurax account "johannes.frenzel@rub.de" but solely provided my github account name. Creating a new "jmfrenzel@example.com" would not provide the admin role. Could you please resolve this for one or the other account. Thanks again.

**Comment by julesies** [comment]
@jmfrenzel can you check your status? you should have access now.

**Comment by julesies** [comment]
@jmfrenzel actually not quite ready...we are waiting for a merge -hopefully resolved today but I'll let you know when it's done!

**Comment by jmfrenzel** [comment]
@julesies,  I have access. Thank you.

**Comment by julesies** [comment]
@jmfrenzel excellent, thank  you!
