### ISSUE TITLE
Search results view doesn't have lines (seems less readable)

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#158]
### Descriptive summary
The search results page has changed and I'm not sure if it's intentional or not. It does seem less readable with lots of whitespace and the loss of separating lines between results. 

Before shot in 2.0: 
![screen shot 2018-01-16 at 4 11 20 pm](https://user-images.githubusercontent.com/4356335/35012756-e14f4b58-fad8-11e7-919a-63c1d4e44f8c.png)

Currently: 
![screen shot 2018-01-16 at 4 18 41 pm](https://user-images.githubusercontent.com/4356335/35012784-f720cec0-fad8-11e7-9349-602c1bd74c9d.png)

Example see: https://nurax.curationexperts.com/catalog?locale=en&q=&search_field=all_fields 

cc @vantuyls

**Comment by jcoyne** [comment]
This looks like an accessability fix to me. The metadata was moved from a table (`<table>`) layout to a definition list (`<dl>`)

**Comment by vantuyls** [comment]
@jcoyne do you know where the design for this UI change came from, or if it was ever mocked up?

**Comment by no-reply** [comment]
This seems related to https://github.com/curationexperts/nurax/issues/129.

It doesn't look like it was intended as a UI change, but as an accessibility fix that discounted UI impacts. I think this ticket should be high priority for `2.1.0`, and the accessibility fix should stay intact.

**Comment by julesies** [comment]
moved to hyrax

**Comment by julesies** [comment]
This look much better! thank you! @vantuyls wanna confirm? Ready to close IMO!

**Comment by vantuyls** [comment]
looks great. thanks!
