### ISSUE TITLE
Add eporter to Repo Administrator

### ISSUE THREAD

**Issue by eporter23** [samvera-labs/nurax-pre2023#159]
### Descriptive summary
Add (existing) eporter at emory dot edu Nurax account to the Nurax Admin group.

### Rationale
To assist with new adopter product research and testing, and understanding roles and permissions

### Expected behavior
Admin access/ability to see all the things!

### Actual behavior
Limited access

### Steps to reproduce the behavior
1. Do this - add the specified eporter account to the admin group
1. Then do this... notify the specified email address when available

### Related work
please see recent tickets for other users wanting admin access to the demo environment

**Comment by julesies** [comment]
@eporter23 can you check your status, you should have admin access now!

**Comment by eporter23** [comment]
Thanks for the quick response! My eporter at emory dot edu account still seems to have basic depositor access only, however - below are the only things I can see: 
![screen shot 2018-01-22 at 9 01 51 am](https://user-images.githubusercontent.com/13855987/35224440-fd1b859e-ff52-11e7-9580-fabfdb512b6f.png)
.

**Comment by julesies** [comment]
Okay sorry @eporter23 - seems like we are waiting for a merge. Let me get back to you!

**Comment by eporter23** [comment]
No problem @julesies, thanks!

**Comment by julesies** [comment]
@eporter23 can you test again? Thanks!
