### ISSUE TITLE
Add new admin user

### ISSUE THREAD

**Issue by vantuyls** [samvera-labs/nurax-pre2023#163]
Nestor Walker at UVA needs to be admin on nurax - he is tech leading the Analytics development effort and will want to use Nurax to review UI changes etc.

naw4t@virginia.edu

**Comment by no-reply** [comment]
Was this closed by https://github.com/curationexperts/nurax/pull/164 ?

**Comment by elrayle** [comment]
I see naw4t in the list of admin users.
