### ISSUE TITLE
Stats filter resets locale to default   

### ISSUE THREAD

**Issue by jmfrenzel** [samvera-labs/nurax-pre2023#165]
### Descriptive summary
Locale falls back to default upon setting stats filter 

### Expected behavior
Locale are kept unchanged   

### Actual behavior
Locale is set to the default one (en)

### Steps to reproduce the behavior

1. https://nurax.curationexperts.com/admin/stats?locale=de  
1. set locale to German 
1. press "Load stats" button

**Comment by julesies** [comment]
@jmfrenzel can you verify this is working now?

**Comment by jmfrenzel** [comment]
Yes it is working,  @julesies 

PS: page still missing full internationalization :eyes: #247
