### ISSUE TITLE
Requesting work stats resets locale to default 

### ISSUE THREAD

**Issue by jmfrenzel** [samvera-labs/nurax-pre2023#166]
### Descriptive summary
Locale falls back to default upon requesting work stats.

### Expected behavior
Locale persists 

### Actual behavior
Locale is set to the default one (en)

### Steps to reproduce the behavior

1. https://nurax.curationexperts.com/works/7s75dc377/stats
1. Change locale to German 
1. Press the Stats button  

### Related work
Closely related issue #165

**Comment by julesies** [comment]
Can you check this is now working @jmfrenzel ?

**Comment by jmfrenzel** [comment]
Yes, it is working @julesies
