### ISSUE TITLE
Add Cloud Files Doesn't work

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#169]
### Descriptive summary

When going to Add Cloud Files, you just get a grey screen

![screen shot 2018-02-12 at 2 44 09 pm](https://user-images.githubusercontent.com/4356335/36116163-5eb2d3b4-1003-11e8-8b8b-0404d2bf84c9.png)

**Comment by jrgriffiniii** [comment]
I can investigate this and capture any bugs using https://github.com/samvera/browse-everything

**Comment by julesies** [comment]
moved to hyrax

**Comment by julesies** [comment]
fixed - was set up issue
