### ISSUE TITLE
Come up with a way to handle config files with sensitive values

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#17]
breaking up remaining tasks mentioned in #13 into separate issues

**Comment by acozine** [comment]
I've got Capistrano shared files set up on demo.curationexperts.com. Passwords and other sensitive values in these files are not checked into github. Changes to these files in github will not be deployed to the server. Currently the shared files are: 
- blacklight.yml
- database.yml
- fedora.yml
- role_map.yml
- secrets.yml
- solr.yml

**Comment by mjgiarlo** [comment]
We think this is done now. Folks should work directly with @acozine to make changes to config/*.yml files.
