### ISSUE TITLE
Admin account for testing

### ISSUE THREAD

**Issue by mcdowney** [samvera-labs/nurax-pre2023#173]
Hi, I'm requesting admin access so that I can help out with testing. Email account: moira.downey@duke.edu (I already have a Nurax account with that email address; if a fresh account is needed, moira.downey@gmail.com will work). Thanks!

**Comment by julesies** [comment]
Can the person who does this add both adam.arling@northwestern.edu and moira.downey@duke.edu to the repo-admin yml file?

@adamjarling

**Comment by mark-dce** [comment]
@julesies - anyone with write access to the repository should be able to add names to the [nurax/config/role_map.yml](https://github.com/curationexperts/nurax/blob/master/config/role_map.yml) file - you can even make the PR changes live in the GitHub Browser UI by clicking on 'Edit this File' (pencil icon) and adding the appropriate e-mail address to the production admin list.

Currently, the following folks have rights to do this:
jcoyne
Justin Coyne
 
mjgiarlo
Michael J. Giarlo
 
geekscruff
Julie Allinson
 
phuongdh
Phil Dinh
 
cam156
cam156
 
starsplatter
Jenn Colt
 
julesies
Julie Rudder
 
elrayle
E. Lynette Rayle
 
smithjp
 
vantuyls
Steve Van Tuyl

**Comment by julesies** [comment]
@mcdowney and @adamjarling can you check your privs on nurax now??

**Comment by adamjarling** [comment]
@julesies Looks like it's working for me.  Thanks.

**Comment by mcdowney** [comment]
@julesies same here. Thanks!

**Comment by julesies** [comment]
fixed!

**Comment by nikdragovic** [comment]
Hi, hoping to reopen this issue to obtain an admin account of my own for testing. I have nikdragovic@gmail.com as an existing Nurax account, or could use nik.dragovic@emory.edu . Thanks!
