### ISSUE TITLE
Typos on Collection Branding

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#174]
### Descriptive summary

That is spelled wrong here, need a space after or and before PNG. 
"For best results, upload an image (JPG, GIF orPNG) taht is 40 pixels in height"

For this one, should it be collection Plate? 
One or more images to be displayed at the top of the collection pate. 

![screen shot 2018-02-13 at 2 42 05 pm](https://user-images.githubusercontent.com/4356335/36170031-1a99bfa2-10cc-11e8-8482-6c353f79594b.png)

**Comment by elrayle** [comment]
Typo on first line...  `and/ro` should be `and/or`

**Comment by elrayle** [comment]
Typo on first line in Logo section...  `collection pate` should be `collection page`

**Comment by julesies** [comment]
https://github.com/samvera/hyrax/pull/2656 looks like this has a fix

**Comment by elrayle** [comment]
Fixed by PR https://github.com/samvera/hyrax/pull/2656

**Comment by julesies** [comment]
confirmed fixed.
