### ISSUE TITLE
Collection type creation loses settings if you add a participant before a save.

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#178]
### Descriptive summary
When creating a Collection Type, if you select/deselect settings, then don't hit save, then click to the participants tab, then add a participant, when you return to the "settings" tab, your settings have returned to default. I can see this leading to some mistakes and having to delete collection types since they can't be edited after created. So I think this is important to address somehow. 

### Expected behavior
Selections are retained as you move through tabs or there is a warning given. 

### Steps to reproduce the behavior

1. Create a collection type
2. Add title, hit save
3. Go to settings: Change the Settings, don't click save
4. Go to participants: add a partcipant
5. Go to Settings: See defaults back.

**Comment by adamjarling** [comment]
@julesies I'm not seeing this behavior locally.  Maybe it's something on Nurax?  Is it possible for me to get a login for Nurax for testing?   Thanks...

**Comment by julesies** [comment]
@adamjarling you can create an account on nurax yourself, and then add a ticket to get repo admin permissions which consists of editing a yml file. ping me if you do this as I want to get another person admin privs at the same time!

**Comment by adamjarling** [comment]
@julesies Great, thanks.  I just signed up under 'adam.arling@northwestern.edu'.  Where would I add the ticket to gain admin privileges?   Or if you're handling for another person, feel free to lump me in with the request.

**Comment by elrayle** [comment]
Copied to Hyrax:  https://github.com/samvera/hyrax/issues/2672

**Comment by cjcolvar** [comment]
@julesies @elrayle What do you think expected behavior should be?  An alert saying you have unsaved changes when you navigate to the participants tab?  Or that any submit (Add or Remove) on the participants tab saves changes on the other tabs?  Or maybe some other behavior?

**Comment by cjcolvar** [comment]
This same problem exists for Collection edit as well, but it looks like Work edit stages all of the sharing changes until the Save Changes button is clicked.
I wonder if Collection Type edit and Collection edit should be changed to work the same, but that seems like a decent amount of work at this point.

**Comment by julesies** [comment]
@cjcolvar @vantuyls @elrayle I agree that consistency with works would be great. but for this round understandable if it doesn't happen. I think I would vote for "An alert saying you have unsaved changes when you navigate to the participants tab" but either would be ok. Just so its clear, clicking SAVE on the participants tab does save the previous settings, but a user is disinclined to hit save on that tab because they can see the participant changes have taken place.

**Comment by cjcolvar** [comment]
FWIW It looks like relationships on work edit share the same behavior such that there isn't an alert and changes can be lost.

**Comment by cjcolvar** [comment]
@julesies @elrayle Seeing as this same behavior is present in other places predating collection extension work could this be dropped from a MustFix/Blocker to a lower severity?

**Comment by julesies** [comment]
works great!
