### ISSUE TITLE
Deactivate Embargoes for Selected Fails

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#180]
### Descriptive summary

In the [Manage Embargoes page](https://nurax.curationexperts.com/embargoes, from the Expired Active Embargoes tab, users have the option to select multiple works and filesets and deactivate their embargoes in bulk. 

### Actual behavior

Select a few embargoes to deactivate:
![image](https://user-images.githubusercontent.com/24395592/36320606-5c85ca5e-130c-11e8-8778-7ecab13766a6.png)

Click Deactivate Embargoes for Selected: 
![image](https://user-images.githubusercontent.com/24395592/36320639-7557bf06-130c-11e8-8137-701647feace1.png)

**Comment by julesies** [comment]
confirmed and moved to hyrax

**Comment by elrayle** [comment]
This only happens when you try to deactivate a File embargo.  It does not happen for works.

Log errors...
```
NoMethodError (undefined method `copy_visibility_to_files' for #<FileSet:0x0055df0978a9e0>):
[2018-03-01T15:06:10.477403 #3223] FATAL -- : activemodel (5.1.5) lib/active_model/attribute_methods.rb:432:in `method_missing'
/opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-eb16822e9e4e/app/controllers/concerns/hyrax/embargoes_controller_behavior.rb:28:in `block in update'
/opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-eb16822e9e4e/app/controllers/concerns/hyrax/embargoes_controller_behavior.rb:26:in `each'
/opt/nurax/shared/bundle/ruby/2.3.0/bundler/gems/hyrax-eb16822e9e4e/app/controllers/concerns/hyrax/embargoes_controller_behavior.rb:26:in `update'
```

**Comment by elrayle** [comment]
Hyrax issue https://github.com/samvera/hyrax/issues/2676

**Comment by julesies** [comment]
@chrisdaaz can you confirm fixed?

**Comment by chrisdaaz** [comment]
works now! thanks @julesies @elrayle @jenlindner
