### ISSUE TITLE
Universal Viewer Bug: Clicking iiif icon throws error

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#186]
clicking the iiif icon throws error. This is located under the share menu as see here:

![screen shot 2018-02-27 at 3 51 57 pm](https://user-images.githubusercontent.com/4356335/36754244-7516b696-1bd6-11e8-8d91-222c0ded8049.png)

**Comment by julesies** [comment]
Manifest can be seen here: https://nurax.curationexperts.com/concern/images/d217qp54p/manifest

**Comment by cjcolvar** [comment]
I think this is due to a bug in UV that can be worked around by removing the unnecessary locale query param from here: https://github.com/samvera/hyrax/blob/master/app/views/hyrax/base/_representative_media.html.erb#L5
I'll work on this tomorrow.
