### ISSUE TITLE
Editing a collection through Edit collection option in Actions menu fails

### ISSUE THREAD

**Issue by Karthikeya212** [samvera-labs/nurax-pre2023#188]
### Descriptive summary
Browser: Chrome 64.0.3282.140
OS: Windows 10
Use Case Number: C_1.4
Issue: If a user tries to edit a collection details through the "Edit collection" option in Actions menu, it fails to save the changes and returning an error page. Whereas, the user can perform the same action properly through the "Edit collection" button in collections home page.

### Expected behavior
User should be able to edit collection using the Edit collection option in Actions menu.

### Steps to reproduce the behavior

1. Login to nurax system either as an Admin or Non-admin user.
2. Make sure that you have some previously created collections, if not create one.
3. From the Dashboard, click on Collections in the sidebar.
4. Click the Actions menu (far right beside a collection) and select Edit collection
5. Edit any of the fields present.
6. Click Save changes button. User will be navigated to an error page
![image](https://user-images.githubusercontent.com/25850972/36805679-0ad01410-1c8c-11e8-84fd-2054a4ed7264.png)
7. Also the changes will not be saved if you re-open the application.

**Comment by julesies** [comment]
@Karthikeya212 can you send a link to the collection you tried to edit? I can't reproduce this and want to see your collections settings. Thanks!

**Comment by julesies** [comment]
@Karthikeya212 nevermind, I got the error.

**Comment by elrayle** [comment]
Fixed by PR https://github.com/samvera/hyrax/pull/2729

**Comment by julesies** [comment]
@Karthikeya212 would you mind confirming fixed?

**Comment by Karthikeya212** [comment]
Looks good to me.
