### ISSUE TITLE
Verification steps fails for non-existing users while sharing access to the collection

### ISSUE THREAD

**Issue by Karthikeya212** [samvera-labs/nurax-pre2023#189]
### Descriptive summary
Browser: Chrome 64.0.3282.140
OS: Windows 10
Use Case Number: CS_1.1
Issue: If the user tries to add a non-existing user in any of the Manager/Depositor/Viewer roles to share the collection, the system fails to recognize that the user is not present and adds the user ID to that specific role

### Expected behavior
If the user is not present in the system, there should be a message below the search box stating 'No matches found'

### Steps to reproduce the behavior

1. Login to the nurax system and open a collection or create a new one.
2. Go to the Sharing tab of the collection.
3. In the Add user search box, enter a random user name/mail which is not present in the system.
4. Select a role for that user and click on Add button.
5. The user name/mail though not present in the system gets updated in that respective role.
![image](https://user-images.githubusercontent.com/25850972/36807561-51d1438e-1c91-11e8-959b-9f10f2079310.png)

**Comment by julesies** [comment]
@vantuyls any thoughts on 2.1?

**Comment by julesies** [comment]
@Karthikeya212 can you retest, the fix is on nurax.

**Comment by Karthikeya212** [comment]
The system is not accepting non-existing users anymore, but I can still add an empty user to the collection.

![image](https://user-images.githubusercontent.com/25850972/37986110-a9720e6a-31c8-11e8-8550-db652c686411.png)

Also one more question, does the same situation valid for user groups. I mean will there be a check for user group as well if it exists or not?

**Comment by Karthikeya254** [comment]
Is this ticket ready to retest, because I am still seeing the issue mentioned in above comment?

**Comment by julesies** [comment]
@elrayle see @Karthikeya212 comment, is there more here to test? Doesn't seem fully resolved.

**Comment by elrayle** [comment]
Adding an empty user seems like a separate issue from the one involving non-existent users.  We'll need a new issue in hyrax to get this addressed.

@Karthikeya254 Are the steps to reproduce...
1. Login to the nurax system and open a collection or create a new one.
1. Go to the Sharing tab of the collection.
1. Select Depositor in Select a role... droplist
1. DO NOT select a user
1. Click Add button without setting a user first.

NOTE: A row gets added to the Depositor list without any user data.

I did these same steps for admin sets and they throw an exception.  So I tried with works.  They don't do anything bad, but they also don't provide any feedback.

At a bare minimum, seems like the Add button should be disabled unless both fields have values.

**Comment by Karthikeya212** [comment]
@elrayle Yeah the steps are correct, and I checked it for collection types User Collection/Multi Membership Collection and both show this issue.

**Comment by Karthikeya212** [comment]
@elrayle Could you please also comment on adding a non existing Group, if it is a valid case or it should also throw an exception?

**Comment by elrayle** [comment]
It should not allow a non-existing group to be added.  I checked Admin Sets and confirmed that it also has this problem.  But Works do not.  They have a select list of possible groups.

**Comment by julesies** [comment]
still open pending https://github.com/samvera/hyrax/issues/2937

**Comment by julesies** [comment]
closed due to moved to hyrax.
