### ISSUE TITLE
Finish configuring GeoNames, BrowseEverything, and Google Analytics 

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#19]
Use accounts set up in #18 

breaking up remaining tasks mentioned in #13 into separate issues

**Comment by acozine** [comment]
Once we have the credentials for these services, add the configs for them to the Capistrano shared files list so we use the secret versions of those files on the sandbox.

**Comment by mjgiarlo** [comment]
@julesies is going to be working on this with @acozine on Monday, at which time I'll put in a new PR that finishes this up.
