### ISSUE TITLE
User with Viewer role in a collection has Add to Collection button in admin show page

### ISSUE THREAD

**Issue by Karthikeya212** [samvera-labs/nurax-pre2023#190]
### Descriptive summary
Browser: Chrome 64.0.3282.140
OS: Windows 10
Use Case Number: CS_1.3
Issue: User with Viewer role in a collection has Add to Collection button in admin show page.

### Expected behavior
User with Viewer role should not have any action buttons in the admin show page of that collection.

### Steps to reproduce the behavior

1. Login as User_1 and create a collection.
2. Add a new user (User_2) to the Viewer role through the sharing tab of that collection.
![image](https://user-images.githubusercontent.com/25850972/36809992-94b2019c-1c97-11e8-9a3e-9e414890bc27.png)
![image](https://user-images.githubusercontent.com/25850972/36810030-a928bf30-1c97-11e8-8062-db51a6964968.png)

3. Logout and Login as User_2, click Dashboard -> Collections -> Managed Collections.
4. Go to the shared collection and click on the title which open an admin page of that collection.
5. User can see the Add to Collection button in top right, which is not supposed to be there.
![image](https://user-images.githubusercontent.com/25850972/36809960-7efeec84-1c97-11e8-9b3f-a1c7f398dd53.png)

**Comment by julesies** [comment]
Verified

**Comment by julesies** [comment]
can you retest @Karthikeya212 ?

**Comment by Karthikeya212** [comment]
Retested
