### ISSUE TITLE
Viewer of an admin set cannot see private works

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/nurax-pre2023#191]
### Reporting for
- Testing for Hyrax 2.1.0 beta 1
- Browser: Chrome Version 64.0.3282.167 (64-bit)
- Admin Sets and Workflow testing (AS 1.14)

### Descriptive summary
When logged in as a Viewer of an admin set, when going to the URL of the work this error is displayed:

![viewertest](https://user-images.githubusercontent.com/4314914/36815651-350860b2-1c90-11e8-822f-4efb18302901.png)

### Expected behavior
Viewers should be able to view private works.

**Comment by julesies** [comment]
verified. In addition, as a viewer, when I click on the admin set in Managed Collections, I get that same error.

**Comment by chrisdaaz** [comment]
this is still behaving as it was reported:

After adding bunny@bunny.bunny as a viewer of https://nurax.curationexperts.com/admin/admin_sets/n009w230h 

![image](https://user-images.githubusercontent.com/24395592/39782962-3c81a8b0-52d9-11e8-868b-f6ee90dd7419.png)

the viewer can see the admin set under the managed collections tab:

![image](https://user-images.githubusercontent.com/24395592/39783000-5a628c6e-52d9-11e8-851b-5103769a3264.png)

but cannot view the (private) admin set: 

![image](https://user-images.githubusercontent.com/24395592/39783024-6d7d9e92-52d9-11e8-84d4-6bf304fb385a.png)

or see any [private works in the private adminset via direct URL](https://nurax.curationexperts.com/concern/images/fb494841c)

![image](https://user-images.githubusercontent.com/24395592/39783090-99ca4004-52d9-11e8-9fc7-2211f6af273a.png)

**Comment by laritakr** [comment]
@chrisdaaz @julesies If I add a viewer to the admin set and create a new private work, the viewer has read access to the new work. Permissions are not applied retroactively to works so the change applies only to new works. 

So the only problem here would be if we expect the viewer to see the admin set itself.

**Comment by elrayle** [comment]
I am unclear exactly which problem this issue is reporting.  Can you list the steps to reproduce the problem you want tested to show that this issue is fixed?

NOTE: The second problem reported in the discussion where an admin set viewer was not able to view the admin set's show page will be fixed by Hyrax PR https://github.com/samvera/hyrax/pull/3056

**Comment by chrisdaaz** [comment]
i think we didn't realize that **permissions are not applied retroactively to works**

i think we can close.

**Comment by julesies** [comment]
https://github.com/samvera/hyrax/pull/3056
