### ISSUE TITLE
Admin Not able to Create New Batch of Works

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/nurax-pre2023#192]
### Reporting for

- Testing for Hyrax 2.1.0 beta 1
- Browser: Chrome Version 64.0.3282.167 (64-bit)
- Works (W_1.7)

### Test Case
Issue happens if logged in as "admin". Does not occur if logged in as a regular user/manager.

### Descriptive summary
When attempting to “Create Batch of works” (added description, resource type, relationships, visibility (set to Private), added to Admin Set 1, etc.), after checking the “Check deposit agreement” and clicking on “Save” receive the “We're sorry, but something went wrong error message”.

![createbatcherror](https://user-images.githubusercontent.com/4314914/36819647-2136f1ca-1c9f-11e8-91a4-1272e1b863ca.png)

**Comment by julesies** [comment]
Verified

**Comment by julesies** [comment]
update: @elrayle tried this and it worked for her. I got the SWW and the URL was: https://nurax.curationexperts.com/dashboard/shares?locale=en

Going back to my works, these works actually went through.

**Comment by chrisdaaz** [comment]
i got this on chrome / win upon saving a batch of works privately: 

![image](https://user-images.githubusercontent.com/24395592/36870018-494bbb0e-1d63-11e8-9bdd-f0b3d613a6b0.png)

they all went through though, just the weird error message.

**Comment by julesies** [comment]
Errors here:

![screen shot 2018-03-02 at 11 45 54 am](https://user-images.githubusercontent.com/4356335/36910671-61e2d3c6-1e0f-11e8-8cc2-d529987c207d.png)
![screen shot 2018-03-02 at 11 46 06 am](https://user-images.githubusercontent.com/4356335/36910676-64569728-1e0f-11e8-8315-4f9fde79bd38.png)

**Comment by julesies** [comment]
@elrayle ☝️

**Comment by julesies** [comment]
@gamontoya can you test this again please! thanks!

**Comment by gamontoya** [comment]
@julesies Will do!

**Comment by gamontoya** [comment]
@julesies This issue is resolved. Ticket closeable.

**Comment by julesies** [comment]
hooray! thanks!
