### ISSUE TITLE
Viewer see Collections they shouldn't in dashboard.

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#200]
Viewer sees way more collections than they should: I'm using student@example.com

 Note the visibility filter also shows way less than it should given the collections below:

![screen shot 2018-03-01 at 4 20 55 pm](https://user-images.githubusercontent.com/4356335/36870361-d6198012-1d6c-11e8-8f9e-246f5fdd7833.png)

Clicking on a collection in the list gives "Unauthorized" error message.

**Comment by elrayle** [comment]
This is marked ready to retest, but there is a related issue that is not complete...  Issue https://github.com/samvera/hyrax/issues/2760

**Comment by julesies** [comment]
@elrayle I have looked at this and things look better but I have a question....about how these are linking. I'll try to explain here, but we may need to discuss via slack. So same user i'm testing now is student@example.com. Here is what i see now:

![screen shot 2018-03-16 at 11 45 31 am](https://user-images.githubusercontent.com/4356335/37530273-8e99810c-290f-11e8-802d-1b8cb10172d4.png)

I am a depositor for Admin Set 20. When I click on Admin Set 20 I route to this:

![screen shot 2018-03-16 at 11 46 15 am](https://user-images.githubusercontent.com/4356335/37530332-a8158b1c-290f-11e8-9a15-67554eab9958.png)

I am a viewer of "Faculty Collection" and when I click on it I see:

![screen shot 2018-03-16 at 11 47 32 am](https://user-images.githubusercontent.com/4356335/37530414-d8f04646-290f-11e8-9991-4f97e507ec7c.png)

**Comment by elrayle** [comment]
This is the same issue as https://github.com/samvera/hyrax/issues/2760.  In Hyrax 1.0 and 2.0, viewers and depositors for admin sets are given access to works only and do not have access to the Admin Set itself.  The required change to allow them to see the admin show page is to give those same users read access to the admin set.

As this is a change in behavior, it needs further discussion in the community.

**Comment by julesies** [comment]
I'm now not seeing extra collections in my managed tab: same account. As a viewer of these 3 managed collections, I can click on the Collection and see the Collection Edit Page, but when I click on the admin set, it is "You are not authorized to access this page."

![screen shot 2018-05-09 at 12 39 42 pm](https://user-images.githubusercontent.com/4356335/39827542-3981ccb4-5386-11e8-8bcb-5b6b2921da14.png)

**Comment by elrayle** [comment]
This is the same as Issue #121 which is fixed by PR https://github.com/samvera/hyrax/pull/3056 (backport https://github.com/samvera/hyrax/pull/3059)

**Comment by julesies** [comment]
close for dupe
