### ISSUE TITLE
Unauthorized access of Works for transferred ownership

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/nurax-pre2023#202]
### Reporting for

- Testing for Hyrax 2.1.0 beta 1
- Browser: Chrome Version 64.0.3282.167 (64-bit)
- Works (W_1.14)

### Descriptive summary

1. When in the Works view, after accepting transferred ownership, the only action available is "Highlight work on profile".

![transferactionserror](https://user-images.githubusercontent.com/4314914/36872773-3a0d9e26-1d5b-11e8-8a18-a0af9e95d29a.png)

2. When trying to access a Work that has been transferred from an "admin" account, I receive an "unauthorized" error message.

![transferaccesserror](https://user-images.githubusercontent.com/4314914/36872776-3fdfd184-1d5b-11e8-86e9-3d8f61152cd0.png)

### Expected behavior
![transfererror](https://user-images.githubusercontent.com/4314914/36872783-4b5d398e-1d5b-11e8-83b3-89d5c8034ec7.png)

After _accepting_ the transfer of ownership, I should have full control of the work/files.

**Comment by elrayle** [comment]
Could not be reproduced and Hyrax issue https://github.com/samvera/hyrax/issues/2763 has been closed.
