### ISSUE TITLE
Can only download file as an action when Work is deposited using "On Behalf of"

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/nurax-pre2023#203]
### Reporting for
Testing for Hyrax 2.1.0 beta 1
Browser: Chrome Version 64.0.3282.167 (64-bit)
Works: (W_1.15)

### Descriptive summary

The only available Action on a file for a Work that has been uploaded _On Behalf Of_ is **Download**.

![onbehalf](https://user-images.githubusercontent.com/4314914/36873103-52aa723c-1d5c-11e8-94b7-a4999a3af8d5.png)

### Expected behavior

If a work was deposited on my behalf, I should be able to do more than just download the file in the Actions menu.

**Comment by julesies** [comment]
verified. In addition, I'm not seeing it show up on "my works".

**Comment by julesies** [comment]
@gamontoya can you retest this? thanks!

**Comment by gamontoya** [comment]
@julesies Absolutely.

**Comment by gamontoya** [comment]
@julesies This issue has been resolved. This ticket can now be closed.

**Comment by julesies** [comment]
thanks!!!
