### ISSUE TITLE
Unable to play video on Safari (iOS & OSX)

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/nurax-pre2023#204]
### Descriptive summary

Video playback is does not function on Safari (iOS & OSX). 

### Expected behavior

Video to begin playing when the play button is clicked.

### Actual behavior

Video does not play. Error not outputted to video player. Error is reported in console:
**Error Reported:** Unhandled Promise Rejection: [object DOMError]

### Steps to reproduce the behavior

1. Go here - https://nurax.curationexperts.com/concern/parent/r494vk17h/file_sets/6d56zw619
1. Press Play button

**Comment by julesies** [comment]
@brianmcbride can you test this in safari desktop and iOS? thanks!

**Comment by brianmcbride** [comment]
@julesies Success! The video (https://nurax.curationexperts.com/concern/parent/r494vk17h/file_sets/6d56zw619) will now play on Safari desktop version 11.03 and Safari iOS v 11.2.6

**Comment by julesies** [comment]
hooray! I saw the same. thanks!
