### ISSUE TITLE
Editing a work that is not in Default Admin Set - moves the work to that Admin Set

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#206]
If I edit a work that is not in "Default Admin Set", and the Admin Set is then changed to Default Admin Set.

Expected behavior. 
Original Admin set should be retained unless it is manually moved. 

1. navigate to a work that is in an admin set that is not the default one.
2. hit edit
3. change some MD or add a file
4. Save (or look at relationships tab and see the Admin set is changed)

**Comment by elrayle** [comment]
Hmmm, I am suspect that PR https://github.com/samvera/hyrax/pull/2639 which made the default admin set at the top of the list may have had a side effect of selecting it.

I'll take a look.

**Comment by julesies** [comment]
@elrayle confirmed fixed.
