### ISSUE TITLE
Contact form submission is broken

### ISSUE THREAD

**Issue by starsplatter** [samvera-labs/nurax-pre2023#207]
### Descriptive summary

In trying to accessibility testing I was checking the contact form. Received a "something went wrong" error when submitting

### Expected behavior
Submission confirmation

### Actual behavior
Error

### Steps to reproduce the behavior

1. Submit contact form

<img width="1440" alt="screen shot 2018-03-02 at 12 17 54 pm" src="https://user-images.githubusercontent.com/2148239/36912162-e35118f6-1e13-11e8-8f3b-c611d5379116.png">

**Comment by vantuyls** [comment]
Does the contact form need to be set up?

**Comment by julesies** [comment]
contact form is not set up on nurax. Sorry for the confusion @starsplatter
