### ISSUE TITLE
Empty error message box displayed in Edit Work page

### ISSUE THREAD

**Issue by Karthikeya212** [samvera-labs/nurax-pre2023#208]
### Descriptive summary
Browser: Chrome 64.0.3282.140
OS: Windows 10
Use Case Number: CM_1.6
Issue: If a user tries to add a work to multiple collections of type Singe Memebership - C, the system should display an error message stating that this operation cannot be performed. However, when this scenario is reproduced there is an empty error message box that is displayed other than the one with message.

### Steps to reproduce the behavior

Prereq: Create 2 collections of type Single-Membership C
1. From Dashboard -> Works, check box beside any work not already in the two prereq collections
2. Click Add to collection button
3. Choose one of the two prereq collections
4. Verify the work was added to the collection
5. From Dashboard -> Works -> action menu for work added to first collection -> Edit work -> Relationships tab
6. In Collections section, type title of other prereq collection in Add to collection box, select the collections, and click Add button and click Save Changes button
7. Verify the work added to the first was NOT added to second collection and a flash message tells the user why it was not added.
![image](https://user-images.githubusercontent.com/25850972/36908633-c6c510de-1e09-11e8-98f1-bec4e2c6a14c.png)

**Comment by mcdowney** [comment]
This occurs in Safari: Version 11.0.3 (13604.5.6), Mac OS: 10.13.3 as well

**Comment by gamontoya** [comment]
Can replicate on Windows 10 Firefox 58.0.2 (32 bit).

**Comment by chrisdaaz** [comment]
moved to https://github.com/samvera/hyrax/issues/2791

**Comment by julesies** [comment]
@Karthikeya212 can you retest?

**Comment by chrisdaaz** [comment]
this is fixed thank you!!
