### ISSUE TITLE
Rights Statement on Collections Descriptions is Missing

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#209]
### Descriptive summary

When you're creating a Work, Hyrax allows you to declare both a rights statement and apply a license to the work. With collections, there is no option to declare a rights statement to the collection; however, a user can apply a license to the collection.

### Rationale

Collections that are in copyright or in the public domain should be declared as such. This should not be a required field, because works within a collection may have different rights assigned to them.

### Expected behavior

Add a Rights statement field to the Collections metadata edit form. 

### Actual behavior

No option to declare a right statements for a collection.

**Comment by vantuyls** [comment]
Why does a collection need a license OR a rights statement? i'm under the impression that both of these are best applied at the work level. How does a collection-level license or rights statement affect licenses and rights statements for works collected?

**Comment by julesies** [comment]
I think that is a fair question. I believe Collections have all the fields that exist in Generic Work. I would love to remove many of them.

**Comment by chrisdaaz** [comment]
i don't have a strong opinion either way. i agree it's more important at the work level. i was just a bit surprised when i didn't see the option in the collection's "additional fields" list. i asked the metadata group on slack if this is important or desirable.

**Comment by chrisdaaz** [comment]
based on discussion on the metadata slack channel, it is not necessary to have a rights statement on the collection page.
