### ISSUE TITLE
Collection Viewer can add Parent Collection

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#210]
### Descriptive summary

[Collections Sharing & Nesting Test 1.13](https://docs.google.com/spreadsheets/d/1PMYNtRyPDRbWG5vTx2TPR80tKBNKANU7gPimCZRLVWU/edit#gid=661954706)

Collection settings: 
![image](https://user-images.githubusercontent.com/24395592/36922840-eb20159e-1e2e-11e8-8857-59a647572f50.png)

Add to collection is available to Viewer, allowing Viewer to add a Parent:
![image](https://user-images.githubusercontent.com/24395592/36922893-11870c6a-1e2f-11e8-8593-364d4104b285.png)

### Rationale

The Viewer role should not allow users to add parent or sub collections.

**Comment by mcdowney** [comment]
This also occurs in Safari 11.0.3 (13604.5.6), MacOS 10.13.3

**Comment by chrisdaaz** [comment]
no longer able to do this! :) thank you
