### ISSUE TITLE
Search "My shares" gives error messages

### ISSUE THREAD

**Issue by jmfrenzel** [samvera-labs/nurax-pre2023#213]
copy from hyrax: https://github.com/samvera/hyrax/issues/2767
also reported to hyku:  https://github.com/samvera-labs/hyku/issues/1518

### Descriptive summary

/dashboard/shares page is not present in hyrax/nurax/hyku. 

Nurax: QA Testing for Hyrax
Hyrax Version: 2.1.0.beta1
Hyrax Branch: v2.1.0.beta1_qa
Hyrax Revision: 8fe35f54e067fd499a4467b9ccbefa48233d43a2 

Hyku v1.0.0.beta2 Docker 

Firefox 58.0.2 (64-bit) canonical 1.0

### Rationale

This is a bug.

### Expected behavior
Search within the with the option "My shares" selected presents results on my shared work. 
The search fields which allow this selection of "My shares" are located at    
* /             hyrax starting page (eg. see localhost:3000 or https://nurax.curationexperts.com/) and 
* /catalog
* that very field on the top of the Edit dialog of a single work.

### Actual behavior
Search with the  option "My shares" selected directs to /dashboard/shares which is not preset.

### Steps to reproduce the behavior
1. Login
1. Go to  
* /            hyrax starting page (eg. see localhost:3000 or https://nurax.curationexperts.com/)  
* /catalog
* that very field on the top of the Edit dialog of a single work.
1. Then select "My Shares" from the pull down right next to the search "Go" button
1. (optional) enter search term 
1. Press the "Go" button 

### Related work

Link to related tickets or prior related work here.

copy from hyrax: https://github.com/samvera/hyrax/issues/2767
also reported to hyku:  https://github.com/samvera-labs/hyku/issues/1518

**Comment by chrisdaaz** [comment]
here's a screenshot of the bug: 
![image](https://user-images.githubusercontent.com/24395592/36997080-1d09a2ea-207e-11e8-8de3-5a76997c5cba.png)

i'm not sure what "my shares" is supposed to search.

**Comment by jmfrenzel** [comment]
I guess "my shares" is that work(s) which the user is sharing with others.

**Comment by julesies** [comment]
The fix was to remove the "my shares" from the drop down. Confirmed this fix.
