### ISSUE TITLE
Collections - index: Select Add Works button on the Collection page is not found.

### ISSUE THREAD

**Issue by jasonchandra** [samvera-labs/nurax-pre2023#220]
### Descriptive summary
Use Case Number C1.5
"* Select Add Works button on the Collection page
* User will be sent to the Works page with Your Works showing.
* User can select from the boxes in the Works table
* Option to Add to Collection appears
* A dialog box appears with options for collections to add the works to
* User can select the collection, update it, and verify that the works have been added on the Collection page"

There isn't an 'add works' button on the collection page, but if i navigate to the works tab, everything else works perfectly.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by chrisdaaz** [comment]
the labels changed to `Deposit new works through this collection` and `Add existing works to this collection`. not a bug. can close.

**Comment by julesies** [comment]
@chrisdaaz need to update the test?

**Comment by julesies** [comment]
will update spreadsheet.
