### ISSUE TITLE
link to user name in transfer notification message leads to 404 error

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/nurax-pre2023#227]
### Descriptive summary

The user name included in a transfer notification is linked to the user profile. But the current linking is broken.

### Rationale

A user name included in a work transfer notification should link to the user profile, because it gives more information to the receiver of the transfer notification about the person who initiated this transaction.

### Expected behavior

When I click on a user name in a transfer notification (in the example below, "hannah.frost@gmail.com"), I expect to go to the user's existing profile.

<img width="1102" alt="screenshot 2018-03-07 23 49 38" src="https://user-images.githubusercontent.com/1801076/37139858-6125e58c-2264-11e8-8313-e2ecf283b36f.png">

### Actual behavior

When I click on a user name in a transfer notification, I get the message; "the page you are looking for doesn't exist".

### Steps to reproduce the behavior

1. User A transfers a work to user B
2. User B views notification about the work transfer initiated by user A
3.  User B clicks on user A's linked name in the notification

**Comment by chrisdaaz** [comment]
moved to https://github.com/samvera/hyrax/issues/2788

**Comment by julesies** [comment]
@hannahfrost can you confirm this is fixed on Nurax? Thanks!

**Comment by hannahfrost** [comment]
Yes, @julesies, it is fixed! I'll close the ticket. Thanks, all!
