### ISSUE TITLE
Unauthorized access to transferred work

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/nurax-pre2023#228]
### Rationale

When a work is transferred to me, I need to be able to edit it. This ticket describes my inability to edit a transferred work that appears on My Works page.

### Expected behavior

I expect to be able to edit a work -- metadata and files -- that has been transferred to me.

### Actual behavior

I see the transferred work on My Works, but I am not able to edit the work.

### Steps to reproduce the behavior

1. Accept a transferred work from another user.
2. Go to My Works page
3. Select the work as listed by checking the box to the left of the work title
4. Click the 'Edit Selected' button that appears above the table
5. See Flash message displayed: "You do not have permission to edit the documents ..."

**Comment by chrisdaaz** [comment]
moved to hyrax https://github.com/samvera/hyrax/issues/2763

**Comment by julesies** [comment]
duplicate issue to https://github.com/curationexperts/nurax/issues/202.
