### ISSUE TITLE
Collections thumbnail is a text input field

### ISSUE THREAD

**Issue by njaffer** [samvera-labs/nurax-pre2023#231]
### Descriptive summary
As a user, I can type anything in the thumbnail field rather than selecting the name of the thumbnail

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Expected behavior
A drop-down list instead of the text field or disabled text field if blank

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related
<img width="1137" alt="screen shot 2018-03-12 at 10 15 07 am" src="https://user-images.githubusercontent.com/12487929/37290117-c34791ae-25e1-11e8-9013-72d3a0777611.png">

**Comment by chrisdaaz** [comment]
this is a search field, allows you to search for works to select for the collection thumbnail

**Comment by julesies** [comment]
@chrisdaaz does this work as expected? or did it change to your knowledge? I thought I remembered a drop down of anything in the collections

**Comment by chrisdaaz** [comment]
@julesies i believe it's working as expected. i think the issue is that @njaffer's collection might not have any works to select from to choose a thumbnail. if we want to disable the text field if the collection does not contain any works, then this would be an enhancement. 

here's what it looks like when you have a collection with works: https://www.screencast.com/t/QP7ZtuwMtQ

**Comment by vantuyls** [comment]
@njaffer can you retest this based on @chrisdaaz's comment?

**Comment by younga3** [comment]
Just retested this on v2.1.0.rc1 nurax. Eg.  https://nurax.curationexperts.com/collections/jm214p238?locale=en  A search on "plant" or "images.jpeg" returns an error if I try to save.

Ldp::BadRequest in Hyrax::Dashboard::CollectionsController#update
javax.jcr.PathNotFoundException: No node exists at path '/prod/pl/an/t/plant' in workspace "default"

**Comment by chrisdaaz** [comment]
this is working now thank you!
