### ISSUE TITLE
Language Changes to English when clicking on fields

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/nurax-pre2023#235]
### Descriptive summary

If a user chooses a language other than English and then clicks on a searchable field in an item record, the language then gets set to English (blacklight) 
https://nurax.curationexperts.com/catalog?f%5Bkeyword_sim%5D%5B%5D=cat

### Expected behavior

The language a user selects stays constant in hyrax.

### Actual behavior

If a user ends up at a blacklight search result the language is set to English.

### Steps to reproduce the behavior

1. Go here https://nurax.curationexperts.com/concern/generic_works/cz30ps70h?locale=de
1. Click on the word cat in the Stichwort field 

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by vantuyls** [comment]
i just spent some time testing this and it seems to happen inconsistently. maybe someone can dig a little deeper to see when this is/isn't happening and report back?

**Comment by chrisdaaz** [comment]
couldn't reproduce, but noticed an issue with user profiles https://github.com/samvera/hyrax/issues/3356
