### ISSUE TITLE
Batch editing permissions fails to update works/files

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#242]
### Descriptive summary

 Batch editing works for changes in permissions is not working. Batch editing works for metadata changes works fine.

I tested adding an editor for 3 works and changing visibility from private to public. both failed. 

### Steps to reproduce the behavior

1. Log in and go to Dashboard: Works
2. Select several works, click Edit
3. Click permissions tab and make changes
4. Go to individual works to see no change.

### Related work

per slack convo could be related to the indexing problems.

**Comment by newmanld** [comment]
As a counterpart to this issue, the "Currently Shared With" is not picking up editors - when the same editor is an editor on all works on the batch.  So one can not use this area in the Permissions tab to add or remove editors, perhaps also other permissions.  Adding editing permissions fails silently - in that it looks like it succeeded when you are on the Permissions tab, but if you go to the individual works the editing rights are not there.  I was testing in  v2.1.0_beta1b_qa on nurax.curationexperts.com

**Comment by elrayle** [comment]
This is ready to retest when changing visibility.  It is still an issue when changing sharing permissions.  Issue https://github.com/samvera/hyrax/issues/2827 is still open to address the sharing permissions problem.

**Comment by julesies** [comment]
Changing visibility via batch is now working consistently. leaving open for 2nd part of the issue.

**Comment by julesies** [comment]
This is working!
