### ISSUE TITLE
Update language on proxy management page

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#248]
### Descriptive summary
The permissions for proxy works a little differently than one expects. current inline help says: 
Select a user who can deposit works on your behalf. You will be the owner of works that this user deposits for you. You can revoke a proxy by clicking the Delete Proxy button.

Suggest changing/adding...

"Select a user who can deposit works on your behalf. You will be able to manage works that this user deposits for you. You can revoke a proxy by clicking the Delete Proxy button, but the proxy will still have edit access to works they deposited until you remove their accounts from each work in the Sharing tab."

This feels wordy, anyone have fewer word ideas?

**Comment by rjkati** [comment]
How about:

"Select a user who can deposit works on your behalf. You can manage works that this user deposits for you. You can revoke a proxy by clicking the Delete Proxy button, but you must remove the proxy's account from each work in the Sharing tab to fully remove their access."

**Comment by julesies** [comment]
Better thanks @rjkati

**Comment by vantuyls** [comment]
looks good. ship it
