### ISSUE TITLE
Show more/less button option not available

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/nurax-pre2023#252]
### Reporting for

- Testing for Hyrax 2.1.0 beta 2
- Browser: Firefox Quantum 59.0.1 (64 bit)
- OS: Windows 7 
- Collections Nesting (CN_1.10)

### Descriptive summary

Added 6 parent collections to a child collection. Verified that all 6 collections are visible, but there is no Show More or Show less button option at the top of the show page.

### Example

- https://nurax.curationexperts.com/collections/5h73pw08c?locale=en

**Comment by vantuyls** [comment]
not clear to me what the expected behavior is - @gamontoya can you point me at an example of the expected behavior elsewhere?

**Comment by gamontoya** [comment]
@vantuyls Unfortunately I cannot. Do note that I was following these steps:

- From Dashboard -> Collections create 3 more collections of type Nestable A
- From Dashboard -> Collections, click the title of 'child collection'
- Add the 3 new collections as parents
- Click Add to collection button (beside Edit and Delete buttons)
- Select a collection from the list of potential parents
   - Click Add to collection
   - Once all 3 added, verify only 3 collections are visible in the parent list at the top of the show page
   -Verify there is a **show more**... button
- Click show more...
- Verify all 6 collections are visible
- Verify there is a ... **show less** button
- Click ... show less
- Verify only 3 collections are visible
- Verify there is a **show more**... button

**Comment by julesies** [comment]
test was updated to reflect the current behavior
