### ISSUE TITLE
Manage Expired Embargos and Expired Leases in User Interface improvement

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/nurax-pre2023#257]
### Descriptive summary

The Manage Expired Embargo page - https://nurax.curationexperts.com/embargoes?locale=en#expired by default has all items checked and ready for deactivation. It might be better to take a different approach and have all items unchecked by default or adding a new button to uncheck/check all items.

### Rationale

If a users only want's to select a couple of items and there are hundreds of items in the list, it becomes time consuming to achieve the task. If the items in the list are not checked by default it would make the managing process easier for repository admins. Or adding a button to check/uncheck the check boxes would have a similar user impact.

### Steps to reproduce the behavior

1. Go here - https://nurax.curationexperts.com/embargoes?locale=en#expired

**Comment by julesies** [comment]
moved to hyrax. closing.

**Comment by vantuyls** [comment]
https://github.com/samvera/hyrax/issues/3178
