### ISSUE TITLE
Adding collection within another collection displays a "Select Collection" dialog box

### ISSUE THREAD

**Issue by gamontoya** [samvera-labs/nurax-pre2023#259]
### Reporting for

- Testing for Hyrax 2.1.0 beta 2
- Browser: Firefox Quantum 59.0.1 (64 bit)
- OS: Windows 7 
- Collections Nesting (CN_1.4)

----------------
### Descriptive summary

When adding an existing collection to a collection, a **Select Collection** dialog box appears above **Select** drop down menu.

![addto](https://user-images.githubusercontent.com/4314914/38443981-7b68e53e-39a2-11e8-9c1d-df9484c021db.png)

----------------
### Expected behavior

Not sure if this is an actual bug as I am not able to confirm that this is expected behavior.

**Comment by vantuyls** [comment]
@elrayle any idea where this design came from? the search box there doesn't seem to function.

**Comment by julesies** [comment]
@vantuyls i think this was introduced unintentionally

**Comment by vantuyls** [comment]
i believe the fix for this is to remove the search box because it does not do anything.

**Comment by julesies** [comment]
@gamontoya can you confirm fixed?

**Comment by gamontoya** [comment]
@julesies This issue is resolved.
