### ISSUE TITLE
Collection count on /dashboard/collections page is wrong

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#275]
### Descriptive summary

As a logged in user, on the collections page, there is text that says how many collections are "in the repository". This text actually only shows the up to the number of collections on the page and only the number of the collections the user has access to. 

### Rationale

It seems that the purpose of this text is to show users how many collections are in the repository. 

### Expected behavior

The number should reflect the number of collections in the repository.

### Actual behavior

(Admin) Displays number of collections on the page: 
![image](https://user-images.githubusercontent.com/24395592/39372804-14ef8744-4a0b-11e8-9e22-4a79ac9f2503.png)

(Admin) Changes when you change the number:
![image](https://user-images.githubusercontent.com/24395592/39372838-3373a70e-4a0b-11e8-8a1e-454819904c82.png)

(User) Only the collection the user has edit access to:
![image](https://user-images.githubusercontent.com/24395592/39373050-f5bee4ae-4a0b-11e8-826e-a0c446a576a6.png)

### Steps to reproduce the behavior

1. Dashboard- > Collections
2. Try to determine how many collections are in the repository

**Comment by julesies** [comment]
@chrisdaaz can you test?

**Comment by chrisdaaz** [comment]
fixed thank you!!
