### ISSUE TITLE
After deactivating embargo, return to work view

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#277]
### Descriptive summary
Right now, if you deactivate a single embargo you go to a Manage Embargo page for that work. It's pretty confusing. What about just going back to the work view page instead?

Current behavior: Click deactivate embargo
![screen shot 2018-05-02 at 3 55 17 pm](https://user-images.githubusercontent.com/4356335/39546309-f19d47a2-4e21-11e8-9734-988640810bf0.png)

User is directed to:
![screen shot 2018-05-02 at 3 55 30 pm](https://user-images.githubusercontent.com/4356335/39546317-f91df670-4e21-11e8-8d30-fd8aebd2b39a.png)

**Comment by vantuyls** [comment]
i  think that would be a less confusing approach. I'm all for it.

**Comment by julesies** [comment]
https://github.com/samvera/hyrax/issues/3244
