### ISSUE TITLE
"Click for more details" shows too much information about work

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#282]
### Descriptive summary

Public visitors of collections see more information than is necessary or even desired when viewing a list of works in a collection and clicking the "more details" arrow.

### Rationale

A public user of a public collection has no need to see the "Edit Access" or "Depositor" metadata of a work when browsing a collection. In some cases, the names, groups, and email addresses of users with edit access to works may be confidential. 

### Expected behavior

Visitors browsing a collection may be interested in more descriptive details about the work itself, such as "Keywords" or "Rights".

### Actual behavior

![image](https://user-images.githubusercontent.com/24395592/39773220-f927a180-52bc-11e8-8925-731507e91347.png)

### Steps to reproduce the behavior

1. As a non-logged in user, visit a [public collection](https://nurax.curationexperts.com/collections/dz010q06g?locale=en)
2. Click on the little arrow to the right of the Work title to view more details.

**Comment by elrayle** [comment]
This is not a change from 2.0 which shows non-logged in users the following work details...

![image](https://user-images.githubusercontent.com/6855473/39774587-4e884c72-52c9-11e8-93fa-ecd1c40d4866.png)

**Comment by elrayle** [comment]
@vantuyls @no-reply @jrr Should this be a blocker?  This is not a change from 2.0 to 2.1, but it is a security issue to reveal to public (non-logged in) users editor ids.

**Comment by julesies** [comment]
I think this was fixed. Closing
