### ISSUE TITLE
Remove "Is part of: `Collection Name` from collection view

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#283]
### Descriptive summary

Users on a collection page can view a list of work titles. Beneath the work titles is a line of text that says that the work is part of the collection. 

### Rationale

This user is already on the collection page and this line of text is redundant.

### Expected behavior

This text is not necessary.

### Actual behavior

![image](https://user-images.githubusercontent.com/24395592/39774299-10db3d16-52c0-11e8-8943-a8ee004fe0bb.png)

### Steps to reproduce the behavior

1. As a non-logged in user, visit a [public collection](https://nurax.curationexperts.com/collections/dz010q06g?locale=en)

**Comment by chrisdaaz** [comment]
fyi.. this is a design issue and not something i am recommending for blocker status. personally, i don't think it's useful to show the names of the collections a work belongs to on the collection page (even when a work belongs to more than one collection) but others may disagree.

**Comment by julesies** [comment]
https://github.com/samvera/hyrax/issues/3243
