### ISSUE TITLE
Rights Statement shows URL in work view

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#30]
Was expecting it to be more human readable, but I'm not sure if this is a bug. When creating a work and you select the Rights Statement, you choose the title of the statement. However on the work view, it's shown as a URL.
See: 
http://demo.curationexperts.com/concern/generic_works/3b5918567?locale=en

**Comment by julesies** [comment]
Likely a Hyrax issue.

**Comment by mjgiarlo** [comment]
This strikes me as a feature request for a future Hyrax 2.x release.

**Comment by vantuyls** [comment]
Submitted at Hyrax for 2.x series: https://github.com/samvera/hyrax/issues/1724

**Comment by mjgiarlo** [comment]
Fixed in Hyrax.
