### ISSUE TITLE
Feature Button does not work

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/nurax-pre2023#314]
### Descriptive summary

The feature a work button does not work in Safari and Chrome on OSX. 

### Rationale

This feature is important for repository managers to be able to feature important works on the primary landing page for a repository. 

### Expected behavior

When a repository manager clicks on the Feature button the work will then be featured on the home page. 

### Actual behavior

The item is not featured on the home page. Nothing appears to happen. 

Console log:

application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:31 [Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details.
(anonymous) @ application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:31
/works/1z40ks975/featured_work.json?locale=en:1 Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:5 POST https://nurax-dev.curationexperts.com/works/1z40ks975/featured_work.json?locale=en 422 (Unprocessable Entity)
send @ application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:5
ajax @ application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:4
(anonymous) @ application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:32
dispatch @ application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:3
g.handle @ application-1aca3c79abf65c4b0ca86f6134f430aa1a080cb85906699cbd740e2a96decefd.js:3

### Steps to reproduce the behavior

1. Go here - https://nurax-dev.curationexperts.com/concern/images/1z40ks975?locale=en#?c=0&m=0&s=0&cv=0&xywh=-1%2C-4%2C532%2C183
1. Click feature

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by julesies** [comment]
is this what you are seeing?
 https://github.com/samvera/hyrax/issues/3169

**Comment by brianmcbride** [comment]
This appears to be a different issue.

**Comment by chrisdaaz** [comment]
i don't see the feature option. can you share a screenshot?

**Comment by chrisdaaz** [comment]
i can't reproduce this on windows, but i'm keeping it for a beta2 test so we'll see if the problem persists.
