### ISSUE TITLE
Deactivate Embargoes for Selected does not work 

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/nurax-pre2023#315]
### Descriptive summary

When a repository manager goes to the Expired Active Embargoes page and attempts to select multiple Works/Files/etc and then clicks to deactivate embargoes for selected, the user is presented with an error page.

### Rationale

A repository manager would find this feature very useful to assist in managing embargoes.

### Expected behavior

Selected items have the attached embargoes deactivated. 

### Actual behavior

User is presented with an error page and embargoes are not deactivated. 

Error:

NoMethodError in Hyrax::EmbargoesController#update
undefined method `values' for nil:NilClass
Extracted source (around line #28):

   def update
      filter_docs_with_edit_access!
      copy_visibility = params[:embargoes].values.map { |h| h[:copy_visibility] }
      ActiveFedora::Base.find(batch).each do |curation_concern|
        Hyrax::Actors::EmbargoActor.new(curation_concern).destroy
        # if the concern is a FileSet, set its visibility and skip the copy_visibility_to_files, which is built for Works

`

### Steps to reproduce the behavior

1. As admin go here - https://nurax-dev.curationexperts.com/embargoes?locale=en#expired
1. Select multiple items, then click deactivate embargoes for selected

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by jmfrenzel** [comment]
can't reproduce after https://github.com/samvera/hyrax/issues/3423#issuecomment-440398311 
might have the same problem as https://github.com/samvera/hyrax/issues/3423

**Comment by chrisdaaz** [comment]
worked for me
