### ISSUE TITLE
Deactivate Leases for Selected does not work

### ISSUE THREAD

**Issue by brianmcbride** [samvera-labs/nurax-pre2023#316]
### Descriptive summary

The "Deactivate Leases for Selected" function under the manage leases page does not work. 

### Rationale

The "Deactivate Leases for Selected" function is a useful management tool for repository managers.

### Expected behavior

When a user selects works/files/etc, under the expired active leases tab on the manage leases page, and then clicks on the "Deactivate Leases for Selected" the works/files leases will be deactivated. 

### Actual behavior

When a user selects works/files/etc, under the expired active leases tab on the manage leases page, and then clicks on the "Deactivate Leases for Selected" the works/files users are then presented with an error page.

NoMethodError in Hyrax::LeasesController#update
undefined method `copy_visibility_to_files' for #<FileSet:0x00007f170a0fa2d0>

Extracted source (around line #432):
  else
        match = matched_attribute_method(method.to_s)
        match ? attribute_missing(match, *args, &block) : super
      end
    end

### Steps to reproduce the behavior

1. As repository admin go here - https://nurax-dev.curationexperts.com/leases?locale=en#expired
1. Select multiple works/files
1. Click on Deactivate Leases for Selected button

### Related work

Link to related tickets or prior related work here - especially link to Hyrax issues that are duplicates or related

**Comment by chrisdaaz** [comment]
same issue as https://github.com/samvera/hyrax/issues/3442
