### ISSUE TITLE
Default Admin Set throws error

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#32]
Default admin set is created. But if you navigate to the admin page where the list of Admin Sets are and click on the Default Admin set, you get a "something went wrong" error.

**Comment by mjgiarlo** [comment]
Confirmed in Nurax, though didn't see this in another Hyrax app I generated. @acozine can you dig up this error from the Rails logs? You should be able to grep for something like `https://demo.curationexperts.com/admin/admin_sets/admin_set%2Fdefault?locale=en` and scan for 5xx/4xx errors.

**Comment by mjgiarlo** [comment]
Fixed today by adding `PassengerAllowEncodedSlashes on` to `/etc/apache2/conf-available/passenger.conf`
