### ISSUE TITLE
Error when trying to create works or collections

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#321]
### Descriptive summary
Can move this to Hyrax if it's hyrax, LMK!  This appears on -dev only, testing on -stable works as expected. 

**When trying to create a work or collection on nurax-dev.curationexperts.com you receive the error:** 

RSolr::Error::Http - 401 Unauthorized Error: {"responseHeader":{"status":401,"QTime":97},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],"msg":"RunExecutableListener is deprecated and disabled by default for security reasons. Legacy applications still using it must explicitely pass '-Dsolr.enableRunExecutableListener=true' to the Solr command line. Be aware that you should really disable API-based config editing at the same time, using '-Ddisable.configEdit=true'!","code":401}} URI: http://127.0.0.1:8983/solr/nurax/update?wt=json&commit=true Request Headers: {"Content-Type"=>"application/json"} Request Data: "[{\"system_create_dtsi\":\"2019-01-17T17:12:21Z\",\"system_modified_dtsi\":\"2019-01-17T17:12:21Z\",\"has_model_ssim\":\"GenericWork\",\"id\":\"sx61dm430\",\"accessControl_ssim\":\"e154516b-80dc-4409-8598-276539e1ea85\",\"depositor_ssim\":\"jrudder@email.unc.edu\",\"depositor_tesim\":\"jrudder@email.unc.edu\",\"title_tesim\":\"test\",\"title_sim\":\"test\",\"date_uploaded_dtsi\":\"2019-01-17T17:12:21Z\",\"date_modified_dtsi\":\"2019-01-17T17:12:21Z\",\"isPartOf_ssim\":\"admin_set/default\",\"on_behalf_of_ssim\":\"\",\"creator_tesim\":\"test\",\"creator_sim\":\"test\",\"keyword_tesim\":\"test\",\"keyword_sim\":\"test\",\"rights_statement_tesim\":\"http://rightsstatements.org/vocab/InC/1.0/\",\"thumbnail_path_ss\":\"/assets/work-ff055336041c3f7d310ad69109eda4a887b16ec501f35afc0a547c4adb97ee72.png\",\"suppressed_bsi\":false,\"generic_type_sim\":\"Work\",\"visibility_ssi\":\"restricted\",\"admin_set_sim\":\"Default Admin Set\",\"admin_set_tesim\":\"Default Admin Set\",\"human_readable_type_sim\":\"Generic Work\",\"human_readable_type_tesim\":\"Generic Work\",\"edit_access_group_ssim\":\"admin\",\"nesting_collection__pathnames_ssim\":\"sx61dm430\",\"nesting_collection__deepest_nested_depth_isi\":1}]" Backtrace: /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive' (eval):2:in `post' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:94:in `update' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:113:in `add' /opt/nurax/shared/bundle/ruby/2.4.0/gems/active-fedora-12.0.2/lib/active_fedora/solr_service.rb:87:in `add' /opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-b5c6605917c0/app/services/hyrax/adapters/nesting_index_adapter.rb:100:in `add_nesting_attributes' /opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-b5c6605917c0/app/services/hyrax/adapters/nesting_index_adapter.rb:78:in `write_nesting_document_to_index_layer' /opt/nurax/shared/bundle/ruby/2.4.0/gems/samvera-nesting_indexer-2.0.0/lib/samvera/nesting_indexer/relationship_reindexer.rb:91:in `block in process_a_document' /opt/nurax/shared/bundle/ruby/2.4.0/gems/samvera-nesting_indexer-2.0.0/lib/samvera/nesting_indexer/relationship_reindexer.rb:109:in `wrap_logging'

**When trying to create a collections you receive:** 

RSolr::Error::Http in Hyrax::Dashboard::CollectionsController#create
RSolr::Error::Http - 401 Unauthorized Error: {"responseHeader":{"status":401,"QTime":55},"error":{"metadata":["error-class","org.apache.solr.common.SolrException","root-error-class","org.apache.solr.common.SolrException"],"msg":"RunExecutableListener is deprecated and disabled by default for security reasons. Legacy applications still using it must explicitely pass '-Dsolr.enableRunExecutableListener=true' to the Solr command line. Be aware that you should really disable API-based config editing at the same time, using '-Ddisable.configEdit=true'!","code":401}} URI: http://127.0.0.1:8983/solr/nurax/update?wt=json&commit=true Request Headers: {"Content-Type"=>"application/json"} Request Data: "[{\"system_create_dtsi\":\"2019-01-17T16:45:52Z\",\"system_modified_dtsi\":\"2019-01-17T16:45:52Z\",\"has_model_ssim\":\"Collection\",\"id\":\"dz010q26z\",\"accessControl_ssim\":\"81d09ea5-7c42-412c-b440-c435f3ee7f42\",\"depositor_ssim\":\"lrobins5@nd.edu\",\"depositor_tesim\":\"lrobins5@nd.edu\",\"title_tesim\":\"Another exhibit\",\"title_sim\":\"Another exhibit\",\"collection_type_gid_ssim\":\"gid://nurax2/hyrax-collectiontype/7\",\"description_tesim\":\"Will it work?\",\"thumbnail_path_ss\":\"/assets/collection-a38b932554788aa578debf2319e8c4ba8a7db06b3ba57ecda1391a548a4b6e0a.png\",\"generic_type_sim\":\"Collection\",\"bytes_lts\":0,\"visibility_ssi\":\"restricted\",\"edit_access_person_ssim\":\"lrobins5@nd.edu\",\"human_readable_type_sim\":\"Collection\",\"human_readable_type_tesim\":\"Collection\",\"nesting_collection__pathnames_ssim\":\"dz010q26z\",\"nesting_collection__deepest_nested_depth_isi\":1}]" Backtrace: /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive' (eval):2:in `post' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:94:in `update' /opt/nurax/shared/bundle/ruby/2.4.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:113:in `add' /opt/nurax/shared/bundle/ruby/2.4.0/gems/active-fedora-12.0.2/lib/active_fedora/solr_service.rb:87:in `add' /opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-b5c6605917c0/app/services/hyrax/adapters/nesting_index_adapter.rb:100:in `add_nesting_attributes' /opt/nurax/shared/bundle/ruby/2.4.0/bundler/gems/hyrax-b5c6605917c0/app/services/hyrax/adapters/nesting_index_adapter.rb:78:in `write_nesting_document_to_index_layer' /opt/nurax/shared/bundle/ruby/2.4.0/gems/samvera-nesting_indexer-2.0.0/lib/samvera/nesting_indexer/relationship_reindexer.rb:91:in `block in process_a_document' /opt/nurax/shared/bundle/ruby/2.4.0/gems/samvera-nesting_indexer-2.0.0/lib/samvera/nesting_indexer/relationship_reindexer.rb:109:in `wrap_logging'
### Steps to reproduce the behavior

1. go to https://nurax-dev.curationexperts.com and try to add a work and a collection.

**Comment by laritakr** [comment]
@bess has resolved this issue, but I don't have authority to close it. @julesies
