### ISSUE TITLE
Notification table doesn't sort on Date properly

### ISSUE THREAD

**Issue by vantuyls** [samvera-labs/nurax-pre2023#33]
The Date field of the notifications table appears to be sorting alphanumerically rather than by time.

## Expected Behavior:
When one sorts the notifications table on the date field, the table should sort on the date field by time

## Realized Behavior:
Sorting notification table on Date sorts the table alphanumerically on the text in the Date field.

Duplicates: https://github.com/samvera/hyrax/issues/1653

**Comment by mjgiarlo** [comment]
OK, since we have the Hyrax issue already, what would y'all think about closing this issue? (Or is it helpful to leave here for other Nurax testers?)

**Comment by mjgiarlo** [comment]
:point_up: Helpful to leave these open 'til confirmed resolved in Nurax.
