### ISSUE TITLE
Grant users ability to tag and resolve issues

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#34]
@acozine can you grant me @julesies and @vantuyls the ability to create and add labels and resolve/close issues here? We are going to triage bugs/confirm and move to hyrax as needed. 

Thank you!

**Comment by acozine** [comment]
@julesies I've invited you and @vantuyls to be collaborators and assigned the two of you admin privileges on this repo. Use your powers for good.

**Comment by vantuyls** [comment]
thanks @acozine
