### ISSUE TITLE
Bread crumb on view page is confusing/misleading

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#38]
When viewing a work (any work, your own or other's) the breadcrumb reads 

My Dashboard>Your Works>Title of work

So it appears that a work from another author is in fact "Yours".

**Comment by mjgiarlo** [comment]
Related to https://github.com/samvera/hyrax/issues/911 though not identical. I suggest we move this issue over to Hyrax.

**Comment by julesies** [comment]
We sure can. I'm less concerned about the "your/my" thing but more about how the breadcrumb navigation is set up to work in general.

for example, As an unauthenticated user, when viewing a work in Hyrax that is not my own - I see breadcrumb "Your works>Title of Work". When I click on that "Your works" - it wants to send me to "My works" and asks me to log in. This seems problematic for authenticated and unauthenticated users alike. See this example: 
https://demo.curationexperts.com/concern/generic_works/ft848q60n?locale=en

Seems like a problem for Digital Collections and IR use cases alike in regards to unauthenticated users.

**Comment by vantuyls** [comment]
i think we down-prioritized this issue over on Hyrax. it is definitely confusing, but probably not breaking for a 2.0 release (?).

**Comment by julesies** [comment]
I would vote this is breaking for unauthenticated users, because they can't actually use it. See screenshot. For authenticated, I could see why it's not considered breaking. 
Breadcrumb problems are SEO problems too, right? 

![screen shot 2017-09-21 at 11 42 40 am](https://user-images.githubusercontent.com/4356335/30704892-05e7bcb6-9ec2-11e7-9711-399b23cf205b.png)
<img width="961" alt="screen shot 2017-09-21 at 11 40 04 am" src="https://user-images.githubusercontent.com/4356335/30704900-0a8ee104-9ec2-11e7-93eb-4d1802f45206.png">

**Comment by mjgiarlo** [comment]
If you're an unauthenticated user and you click on a link labeled "Your Works" or "My Dashboard," what would you expect the link to do?

I agree that those are the wrong breadcrumbs for an unauthenticated user, but I'm on the fence about whether this should be a blocker or not. I could be convinced either way!

**Comment by julesies** [comment]
hmmm....I guess I wouldn't expect breadcrumbs to lead to the dashboard at all, but that you would navigate to that via a menu. I was thinking breadcrumbs should serve the public users first. So public users would never see "Your works". Maybe they would see "Works>Title of Work" or "Collection>Title of work" or "Collection>Works>Title of work"? Not sure I have any brilliant idea for solution, but I do think that breadcrumbs should always be usable by public users.

**Comment by mjgiarlo** [comment]
@julesies OK, that all sounds good. I think we should have this written up as a new Hyrax issue, and solicit input from the Hyrax UI/UX team on best practices around breadcrumbs. I am inclined to get this into 2.1.0 instead of blocking the 2.0.0 release at the moment.

**Comment by julesies** [comment]
@mjgiarlo that sounds good. thanks for hearing me out :) I'll write it for Hyrax.

**Comment by julesies** [comment]
@mjgiarlo upon trying to move this issue to hyrax, I used Safari to capture a screen shot. Turns out the breadcrumbs don't appear in the logged out view in Safari at all - but do in Chrome so maybe it's a Chrome bug actually...I'm going to write up all the behavior in Hyrax...

**Comment by mjgiarlo** [comment]
@julesies I don't see the breadcrumbs when I am logged out either, and I am using Chrome. I'm guessing you saw them due to browser caching. Maybe this is a false positive.

**Comment by julesies** [comment]
was confirmed as bug and is open issue in hyrax
