### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mark-dce** [samvera-labs/nurax-pre2023#4]
Please add the standard community licensing

**Comment by mjgiarlo** [comment]
See Hyrax for example: https://github.com/samvera/hyrax/blob/master/LICENSE

**Comment by mark-dce** [comment]
Actually, shouldn't we be following the pattern here https://wiki.duraspace.org/display/samvera/Code+Copyright+Statement?

**Comment by mjgiarlo** [comment]
For now, I recommend we follow the community convention @mark-dce shared while Steering discusses the alternative implemented in Hyrax.
