### ISSUE TITLE
Citation button routes to dashboard

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#40]
Citations are working, but when you are on a "work view" and click the citation button, you get tossed into the dashboard - then only you can see it. 
![screen shot 2017-09-13 at 9 06 00 pm](https://user-images.githubusercontent.com/4356335/30407653-885372ea-98c7-11e7-815d-155169f81d22.png)

**Comment by mjgiarlo** [comment]
@julesies Pull request that fixes this is here: https://github.com/samvera/hyrax/pull/1687 Once merged, it should auto-close this issue.
