### ISSUE TITLE
Thumbnails are not generating

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#41]
Doesn't seem like any images or pdfs are getting thumbnails 

![screen shot 2017-09-13 at 9 10 51 pm](https://user-images.githubusercontent.com/4356335/30407746-183a0360-98c8-11e7-979b-623fe39ba676.png)

**Comment by mjgiarlo** [comment]
@acozine I wonder if we need to install or update the dependencies that create derivatives, including ImageMagick, ghostscript, and libreoffice?

**Comment by mjgiarlo** [comment]
As of Sept. 21 (deployed atop Hyrax 2.0.0.beta3), we believe this has been fixed.

**Comment by acozine** [comment]
As a breadcrumb for Future Folks, these are the versions of those dependencies installed on the demo server as of today:
`ffmpeg version git-2017-09-08-260ea7a Copyright (c) 2000-2017 the FFmpeg developers`
`GPL Ghostscript 9.19 (2016-03-23)`
`Version: ImageMagick 7.0.7-0 Q16 x86_64 2017-09-07 http://www.imagemagick.org`
`LibreOffice 5.2.2.2 20m0(Build:2)`
