### ISSUE TITLE
Contact form throws error on submission

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#42]
![screen shot 2017-09-13 at 9 13 19 pm](https://user-images.githubusercontent.com/4356335/30407799-75e16fc6-98c8-11e7-803b-6426b786ce6d.png)

**Comment by mjgiarlo** [comment]
@acozine can you dig up this error from the Rails server log? (If this gets annoying, maybe we could look into setting up Honeybadger or something like it?)

**Comment by mjgiarlo** [comment]
Got the error -- we don't have an SMTP server setup. Discussed on Slack. Since none of us have open SMTP servers, we will close this ticket and instruct testers not to test the contact form.
