### ISSUE TITLE
Sign out throws error and doesn't sign out

### ISSUE THREAD

**Issue by vantuyls** [samvera-labs/nurax-pre2023#47]
### Descriptive summary

Signing out of Nurax returns the user to the homepage with an error saying "user sign_out does not exist" and the user is not signed out. 

![screen shot 2017-09-18 at 9 38 17 am](https://user-images.githubusercontent.com/9534576/30553183-40c7cdfe-9c55-11e7-9fda-20476705d2cd.png)

### Expected behavior
Sign out should return user to the homepage as an un logged in user.

### Actual behavior
Sign out returns user to the homepage, still logged in, with an error message.

### Steps to reproduce the behavior

1- log in to nurax
2- log out of nurax
3- see error message

**Comment by julesies** [comment]
confirmed. But i was previously able to sign out on Nurax!
