### ISSUE TITLE
Clicking analytics button on work view throws error

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#54]
### Descriptive summary
When viewing a work, clicking on the analytics button throws "We are sorry something went wrong" error. 

### Expected behavior
It should go to the graph view of the analytics

### Actual behavior
error

### Steps to reproduce the behavior

1. Go to a work
2. Click analytics button

**Comment by mjgiarlo** [comment]
Resolved on Sept. 22 by changing the `privkey_path`, `privkey_secret`, and `client_email` values in `config/analytics.yml`, and then by granting the service account email (what should be in `client_email` above) read/analyze access to our GAnalytics account. It's convoluted, yes! Closing.
