### ISSUE TITLE
Edit Button on File Manager is Broken

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#58]
### Descriptive summary

Was this disabled? It works in Hyrax 1.x.

The Edit button on the File Manager `/file_manager` view does nothing.  

### Rationale

Users expect that the File Manger includes the ability to edit a specific file's properties. The edit button suggests this capability.

### Expected behavior

Clicking these buttons should open the edit file view.

![image](https://user-images.githubusercontent.com/24395592/30765945-bdeb384c-9fb7-11e7-9695-79bf8e984a9b.png)

### Actual behavior

Nothing.

### Steps to reproduce the behavior

1. Go to a work with multiple files.
2. Open the File Manager
3. Click the edit button.

**Comment by mjgiarlo** [comment]
Thanks, @cpd3149! Ticketed in Hyrax: https://github.com/samvera/hyrax/issues/1085

@vantuyls @julesies Do we think this is a blocker for 2.0.0 or not?
