### ISSUE TITLE
Add folder button does not appear in Safari

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#64]
### Descriptive summary
Originally reported by @shlake 
When adding a new work in Safari, you do not see the Add Folder button. You do see it in Chrome.

### Expected behavior
Expect buttons to appear in any browser.

### Actual behavior
Button only appears in Chrome (FF not tested)

### Steps to reproduce the behavior

1. In safari, Add new work
2. Select Image
3. Select files
4. No folder button

Safari:
![screen shot 2017-09-27 at 10 58 00 am](https://user-images.githubusercontent.com/4356335/30920940-353ef3fc-a373-11e7-80a5-7550e3333621.png)
Chrome:
![screen shot 2017-09-27 at 10 58 06 am](https://user-images.githubusercontent.com/4356335/30920946-36fd5292-a373-11e7-9b6c-49bbd2302247.png)

**Comment by mjgiarlo** [comment]
This feature only worked in Chrome. I can verify that this feature now also works in Firefox. I can put in a small patch that will enable it for all browsers, and if we find browsers this *doesn't* work in, we can enter new bug issues we find them. Cool?

**Comment by julesies** [comment]
button appeared for me. thanks @mjgiarlo !!
