### ISSUE TITLE
When trying to add a private work to a collection - throws error

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#69]
### Descriptive summary
I tried to add a bunch of works to a collection I created.  As far as I can tell, it works for any combo of works that are public, embargoed, institution only. But if you try to include a private work either in batch or single, you get "We're sorry, something went wrong"

### Expected behavior
You should either get a warning "Can't add private works" or it should allow you to add private works. 

### Actual behavior
You are permitted to select any work, but including a private work throws error. 

### Steps to reproduce the behavior

1. Dashboard: Collections
2. Add new collection
3. Add private work to collection

![screen shot 2017-09-28 at 9 24 14 am](https://user-images.githubusercontent.com/4356335/30970361-f683e152-a432-11e7-9478-23a684e0b4df.png)

**Comment by julesies** [comment]
@cpd3149 test this one for me?

**Comment by chrisdaaz** [comment]
works for me, can't reproduce: https://www.screencast.com/t/JN1S2EYCskD

**Comment by mjgiarlo** [comment]
@julesies Can you re-test now that #72 is fixed? If you can't reproduce this any longer, can you close both this issue and https://github.com/samvera/hyrax/issues/1751?

**Comment by mjgiarlo** [comment]
Could not reproduce: https://demo.curationexperts.com/concern/generic_works/6969z078d?locale=en
