### ISSUE TITLE
Menu appears on File View page but not on other pages

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#71]
### Descriptive summary
When looking at the File View in Chrome, you see a menu that is not seen on other pages. 

![screen shot 2017-09-28 at 9 28 20 am](https://user-images.githubusercontent.com/4356335/30972021-77ef5650-a437-11e7-966e-52a179a01d4d.png)

### Rationale

It should be consistent. FWIW I like seeing the menu and think it would help with navigation.

### Steps to reproduce the behavior

1: https://nurax.curationexperts.com/concern/parent/sb397824g/file_sets/hd76s004z

**Comment by mjgiarlo** [comment]
@julesies What menu? Can't tell from screenshot or description above what menu you're referring to.

**Comment by julesies** [comment]
@mjgiarlo sorry for any confusion. I'm talking about the top left menu under Hyrax. Home, about, menu, contact. 

Looks like it's also on the Search page, but not on work view or collection view. 

![screen shot 2017-09-29 at 8 31 39 am](https://user-images.githubusercontent.com/4356335/31015948-a34c9ec0-a4f0-11e7-9d45-f63ad6a69115.png)

**Comment by julesies** [comment]
@mjgiarlo @vantuyls did we mean to mark this fix in 2.0? I think I dropped the ball on this one if so.

**Comment by mjgiarlo** [comment]
@julesies @vantuyls I have a fix almost ready. Will push a PR this week.
