### ISSUE TITLE
After log in user is routed to Works only if they already have works deposited

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#73]
### Descriptive summary
As a regular user, who has not deposited works (At least, i think this is the pattern), I am routed to Dashboard instead of Dashboard: Works, where I'll see the new work button. 

### Steps to reproduce the behavior

1. Click Share My work from home page
2. Log in as a user without any works. (new user)
4. Directs to Dashboard

If you log in as a user with works, you get to the right place. 

![screen shot 2017-09-28 at 11 56 06 am](https://user-images.githubusercontent.com/4356335/30977053-6c44b93c-a444-11e7-9980-3e18a15ed3e3.png)

**Comment by mjgiarlo** [comment]
@julesies I don't understand this ticket. Whether I've created works or not, when I click the login button and login, I am taken to the dashboard.

**Comment by julesies** [comment]
So I rewrote the steps so it makes more sense that it's behavior associated with logging in after "Share my work", sorry @mjgiarlo  I'm seeing the behavior I described, but I believe in both cases it should go to "My works" after log in since this ticket: https://github.com/samvera/hyrax/issues/1092

(What I did before was not make it clear that it was from the "share my work" button). Login from other places (search,etc), does direct to dashboard in both cases.

**Comment by mjgiarlo** [comment]
I could not reproduce this via the following steps:

1. Logout existing session
2. Click Share My Work button
3. Login with existing user account with zero deposited files
4. Redirected to /dashboard/my/works

**Comment by chrisdaaz** [comment]
i can't reproduce this either https://www.screencast.com/t/xLEdP7aMeatV

**Comment by julesies** [comment]
No one can reproduce this. closing
