### ISSUE TITLE
Enable Hyrax bonus features

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#8]
Enable the following bonus features for testing:

- [ ] Google Analytics
- [ ] BrowseEverything
- [x] ContactForm (may require 1-2 config tweaks?)
- [x] Citations
- [x] FFmpeg transcoding
- [ ] Geonames
- [x] Turn off requiring files for works
- [x] Virus checking
- [x] Sidekiq for background jobs?
- [x] At least 2 work-types with different fields 

Notes from planning meeting include: 
including getting API keys, generating configuration, etc. (Ideal to use a shared email address for these so not tied to a particular person.)

**Comment by julesies** [comment]
Does this need to be more than one ticket? @mjgiarlo or others LMK and I'll break it up. Also happy to use a different format if there is a preferred one!

**Comment by mjgiarlo** [comment]
@julesies We can do that at a later date -- 'sok for now. I converted the bullets into a task list and I think that ought to suffice for the time being. Thank you!

**Comment by mjgiarlo** [comment]
These features require setting up accounts (and recording credentials/usernames/tokens/etc. in potentially protected files):

* Google Analytics
* BrowseEverything
* Geonames

We need a way to handle setting up shared accounts and storing these values in a way that doesn't expose credentials on GitHub. Cc: @acozine @julesies

**Comment by mjgiarlo** [comment]
For the contact form, where do we want email sent? @julesies

**Comment by mjgiarlo** [comment]
These also require setting up system packages:

* A/V transcoding (`ffmpeg`)
* Virus checking (`clamav`)

**Comment by julesies** [comment]
hyraxrepomanager@gmail.com for the contact form @mjgiarlo

**Comment by julesies** [comment]
@mjgiarlo close this one since I created the others?

**Comment by mjgiarlo** [comment]
@julesies I believe #13 will auto-close this issue once merged. Thanks much for breaking this out into new issues! :tada:
