### ISSUE TITLE
New works added as child works are pending approval and cannot be viewed

### ISSUE THREAD

**Issue by heathergreerklein** [samvera-labs/nurax-pre2023#82]
### Descriptive summary
Works added using "Attach New Work" to create a child work indicate they are pending approval, and cannot be viewed or approved. 

### Expected behavior
New work is added and listed as a child

### Actual behavior
New work is added as "pending approval" and cannot be approved by the depositor, and does not appear as a child of work as intended. The new work also cannot be searched for to add as a child.

### Steps to reproduce the behavior
1 Go to a Work
2 Click on the Edit button
3 Click on the Relations Tab
4 Other Works in the Work heading appears 
5 Click on the Attach New Work Button
6 Create a new Work (add Descriptions, Files)
7 Save the new Work
8 Go back to the first Work
9 Click on Edit
10 The new Work does not appear as a child
11 Click on the notification bell
12 The new work shows as pending approval, click on the new work name
13 The new work does not allow for approval

**Comment by julesies** [comment]
confirmed
