### ISSUE TITLE
Add thumbnail on Admin Set interface doesn't appear

### ISSUE THREAD

**Issue by vantuyls** [samvera-labs/nurax-pre2023#85]
### Descriptive summary

Adding a thumbnail to an admin set is an element of the edit interface and should appear for any user who has ability to edit he admin set.

Chrome - Mac 

### Expected behavior
add thumbnail interface should appear on edit page.

### Actual behavior
add thumbnail interface is not to be found.

### Steps to reproduce the behavior

1. create admin set 
2. edit admin set
3. admin set thumbnail interface is not there

**Comment by julesies** [comment]
@vantuyls this works for me on chrome mac, let's see if any other admin users can't do it. One other thing to check is that there has to first be an image in the admin set for this feature to work (the test might not say this).

**Comment by chrisdaaz** [comment]
is this the interface that's missing? i'm on windows chrome:

![image](https://user-images.githubusercontent.com/24395592/31089017-402cc5ac-a768-11e7-9a61-979f3f53bff6.png)

**Comment by julesies** [comment]
@vantuyls close?
