### ISSUE TITLE
Delete admin set unavailable on Safari-Mac

### ISSUE THREAD

**Issue by vantuyls** [samvera-labs/nurax-pre2023#86]
### Descriptive summary

Admin set edit page allows authorized user to delete the admin set. This button is unselectable.

Mac - Safari Browswer

### Expected behavior

if authorized, the delete button should be selectable.

### Actual behavior
button is not selectable.

<img width="1089" alt="screen shot 2017-09-30 at 10 24 03 am" src="https://user-images.githubusercontent.com/9534576/31047999-b26ac646-a5c9-11e7-94a2-3f13f0f80e58.png">

**Comment by julesies** [comment]
@vantuyls is this because there is a work in the set? If you delete the work, can you delete the set?

**Comment by mjgiarlo** [comment]
I suspect that's what is happening here. If you mouse-over the Delete button, does it give you some indication of why it's greyed out?

**Comment by chrisdaaz** [comment]
it's because there's work in the set. the title text gives the reason:

![image](https://user-images.githubusercontent.com/24395592/31088629-faf6199e-a766-11e7-8ba8-602c3980e74b.png)
