### ISSUE TITLE
As a Manager, I can edit a work pending review, but it doesn't save

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#87]
### Descriptive summary
When logged in as a manager, I go to edit the title of a "Private Work" that is "pending review" and I'm able to edit metadata, but then upon hitting save the edit I made, disappears. 

### Expected behavior
Either I should be able to edit and save, OR I should not be able to edit if that operation is prohibited. 

### Actual behavior
I can edit works in workflow, but changes do not save. 

### Steps to reproduce the behavior

1. Create admin set with one step workflow, add a manager (IMPORTANT TO DO THIS BEFORE WORKS ARE CREATED)
2. As regular user, add a work to that admin set
3. As manager, try to edit metadata for that work just created
4. Hit save

**Comment by julesies** [comment]
@cpd3149 do you mind confirming this one for me?

**Comment by chrisdaaz** [comment]
this is me as a manager of an admin set trying to reproduce the issue: https://www.screencast.com/t/JN1S2EYCskD

it seems i *can* edit the metadata, but i can't see or review the work.

**Comment by julesies** [comment]
same boat at this time! https://github.com/curationexperts/nurax/issues/101

**Comment by mjgiarlo** [comment]
Decided after discussion on https://github.com/samvera/hyrax/issues/1757 to close.
