### ISSUE TITLE
Give admin roles to select users

### ISSUE THREAD

**Issue by julesies** [samvera-labs/nurax-pre2023#9]
Once user accounts are set up, grant admin roles permissions (to access all content, admin sets, etc) to Repo Managers testing facilitators: Julie Rudder, Steve Van Tuyl, Chris Diaz, Sherry Lake, Harsh Parekh

**Comment by mjgiarlo** [comment]
@julesies Can you provide email addresses for all these folks? I'll add them to `config/role_map.yml`

**Comment by mjgiarlo** [comment]
Using these for the time being:

```
    - mjgiarlo@stanford.edu
    - jrudder@email.unc.edu
    - Steve.VanTuyl@oregonstate.edu
    - chris-diaz@northwestern.edu
    - shlakeuva@gmail.com
    - hparekh@nd.edu
```

**Comment by mjgiarlo** [comment]
File another issue to correct any of these or add others. Thanks!
