### ISSUE TITLE
Editing a work removes the collection it was in previously

### ISSUE THREAD

**Issue by laritakr** [samvera-labs/nurax-pre2023#94]
### Descriptive summary
When editing a work that is part of a collection, the collection gets removed after the updated work gets saved.

### Expected behavior
The collection should not be affected when a work is updated.

### Actual behavior
The collection is being removed when a work gets updated.

### Steps to reproduce the behavior

1. Create a work in a collection.
2. Edit the work to add a new keyword, and save.
3. The collection is removed from the work.

**Comment by mjgiarlo** [comment]
Confirmed. The problem seems to be that loading the "Edit work" page does not successfully select the existing collections the work is a attached to.

**Comment by mjgiarlo** [comment]
This needs a corresponding Hyrax ticket.
