### ISSUE TITLE
Restore a prior version of a file doesn't work on Windows

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#95]
### Descriptive summary

This [passed tests on macs](https://docs.google.com/spreadsheets/d/1as8uiM0ofEd_2u2ThFYJQu5IdJ8ipHOOH9NUOngjlj8/edit#gid=786366500), but i can't get it to work on windows for some reason.

### Rationale

Users should be able to upload new versions and restore previous versions, per the UI.

### Expected behavior

Restoring does not work on Windows.

### Actual behavior

When I download the file from the work and file view, it's the new version of the work, but not the restored original version. 

### Steps to reproduce the behavior

Easily test with images (different images, thumbnails, filenames).

1. Create a Work
2. Edit file version (Work > File > Actions > Select 'Versions')
3. Upload a new version of the file  
4. Save
5. Edit file version (Work > File > Actions > Select 'Versions')
6. Select Restore from...
7. Save Revision
8. Go back to work
9. Download the image/ file

**Comment by julesies** [comment]
I'll have Amy at UNC check this tomorrow on Windows

**Comment by h-parekh** [comment]
I can't reproduce this issue on:
* Windows 10 - Firefox 54
* Windows 10 - IE 11
* Windows 10 - Edge 40

I was able to upload a new image, restore previous version and download the restored versions as expected in [this work](https://nurax.curationexperts.com/concern/images/0g354f20t?locale=en)

**Comment by julesies** [comment]
Amy at UNC tested this too and it worked, however you needed a refresh of the page b/w version switch

**Comment by chrisdaaz** [comment]
ok, good, thank you! i think my problem was i was testing the restore download too soon without refreshing, logging in/logging out, etc. closing!
