### ISSUE TITLE
Review Submissions panel shows more works than it should

### ISSUE THREAD

**Issue by chrisdaaz** [samvera-labs/nurax-pre2023#99]
### Descriptive summary

As a non-administrator user with manager participation for an admin set(s), I should be able to review submissions from that(those) admin set(s). Instead, I see way more works from other admin sets in the Review Submissions panel.

### Evidence

These are the admin sets I manage, containing 13 works.

![image](https://user-images.githubusercontent.com/24395592/31195535-44988ba4-a910-11e7-8ce4-afe0a3b35db6.png)

These are the works I can review:

![image](https://user-images.githubusercontent.com/24395592/31195551-52043f40-a910-11e7-8363-6e3181a70334.png)

I can see even more that have been published:

![image](https://user-images.githubusercontent.com/24395592/31195570-62c6c78a-a910-11e7-9c78-7254f45b01d1.png)

### Expected behavior

Managers should only be able to review works in admin sets they manage. 

### Actual behavior

Managers see more works than they have access to.

### Steps to reproduce the behavior

1. Become a manager of an admin set
2. Go to Dashboard -> Review Submissions
3. Are those works in admin sets you manage, or are there more there?

### Related work

cc: @julesies

**Comment by mjgiarlo** [comment]
@vantuyls @julesies Needs triage and ticketing in Hyrax.

**Comment by mjgiarlo** [comment]
@cpd3149 I merged the Hyrax fix, updated Nurax, and reindexed all the objects. Can you re-test this?

**Comment by chrisdaaz** [comment]
@mjgiarlo working as it should thanks!

**Comment by mjgiarlo** [comment]
Excellent!
